### ISSUE TITLE
Inference code for Randlanet 

### ISSUE THREAD

**Issue by abhigoku10** [nicolas-chaulet/torch-points3d#236]
@nicolas-chaulet is there inference pipeline for Randlanet?? thanks in advance

**Comment by nicolas-chaulet** [comment]
Not at the moment unfortunately. We haven’t completely finished to implement randlanet either

**Comment by abhigoku10** [comment]
Thanks for the quick response!! the original repo has good implementation but not able to estimate the inference time due to the usage of iterators

**Comment by abhigoku10** [comment]
@nicolas-chaulet  hads the inference pipeline done ???

**Comment by nicolas-chaulet** [comment]
Nope!

**Comment by sandeepnmenon** [comment]
Is randlanet implementation done?
I wanted to train a randlanet model but with the current repo and command
poetry run python train.py task=segmentation model_type=randlanet model_name=Randlanet_Res dataset=semanticKitti
```
torch-points3d/torch_points3d/trainer.py", line 90, in _initialize_trainer
    self._model: BaseModel = instantiate_model(copy.deepcopy(self._cfg), self._dataset)
  File "/home/menonsandu/torch-points3d/torch_points3d/models/model_factory.py", line 23, in instantiate_model
    resolve_model(model_config, dataset, task)
  File "/home/menonsandu/torch-points3d/torch_points3d/utils/model_building_utils/model_definition_resolver.py", line 10, in resolve_model
    "FEAT": max(dataset.feature_dimension, 0),
  File "/home/menonsandu/torch-points3d/torch_points3d/datasets/base_dataset.py", line 48, in wrapper
    result = func(self, *args, **kwargs)
  File "/home/menonsandu/torch-points3d/torch_points3d/datasets/base_dataset.py", line 426, in feature_dimension
    return self.test_dataset[0].num_features
  File "/home/menonsandu/.cache/pypoetry/virtualenvs/torch-points3d-KHeQYfvV-py3.8/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 116, in num_features
    return self.num_node_features
  File "/home/menonsandu/.cache/pypoetry/virtualenvs/torch-points3d-KHeQYfvV-py3.8/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 111, in num_node_features
    return self[0].num_node_features
  File "/home/menonsandu/.cache/pypoetry/virtualenvs/torch-points3d-KHeQYfvV-py3.8/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 187, in __getitem__
    data = self.get(self.indices()[idx])
IndexError: range object index out of range
```

This is because num_features attribute is not defined in randlanet.yaml
@nicolas-chaulet is randlanet training pipeline pending as well?

**Comment by nicolas-chaulet** [comment]
Hey, we haven't maintained randlanet in a while, it is probably outdated now.

**Comment by Stakhan** [comment]
Hi there !
I've been tasked with running RandLANet for my internship and using your library would be very much pratical. If there is some maintenance needed, I would be happy to provide my help.
For now I have started to get my hands on how the library is built (by reading your documentation and playing with the codebase). I have also read the original paper from Qingyong Hu so I have some understanding of the way each module (Attentive Pooling, Local Spatial Encoding and Dilated Residual Block) should work.
Any hint on what should be checked ?

For now, when I launch it with s3dis1x1 (`python train.py task=segmentation model_type=randlanet model_name=Randlanet_Res dataset=s3dis1x1`), I get the following error :
```
EPOCH 1 / 100
  0%|                                                                                         | 0/1046 [00:17<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    main()
  File "C:\Users\EAL\AppData\Roaming\Python\Python38\site-packages\hydra\main.py", line 20, in decorated_main
    run_hydra(
  File "C:\Users\EAL\AppData\Roaming\Python\Python38\site-packages\hydra\_internal\utils.py", line 171, in run_hydra
    hydra.run(
  File "C:\Users\EAL\AppData\Roaming\Python\Python38\site-packages\hydra\_internal\hydra.py", line 82, in run
    return run_job(
  File "C:\Users\EAL\AppData\Roaming\Python\Python38\site-packages\hydra\plugins\common\utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "train.py", line 13, in main
    trainer.train()
  File "C:\Users\EAL\Documents\prototyping\torch-points3d\torch_points3d\trainer.py", line 140, in train
    self._train_epoch(epoch)
  File "C:\Users\EAL\Documents\prototyping\torch-points3d\torch_points3d\trainer.py", line 194, in _train_epoch
    self._model.optimize_parameters(epoch, self._dataset.batch_size)
  File "C:\Users\EAL\Documents\prototyping\torch-points3d\torch_points3d\models\base_model.py", line 213, in optimize_parameters
    self.forward(epoch=epoch)  # first call forward to calculate intermediate results
  File "C:\Users\EAL\Documents\prototyping\torch-points3d\torch_points3d\models\segmentation\base.py", line 47, in forward
    data = self.model(self.input)
  File "C:\Users\EAL\Anaconda3\envs\testenv4\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\EAL\Documents\prototyping\torch-points3d\torch_points3d\models\base_architectures\unet.py", line 303, in forward
    data_out = self.down(data, **kwargs)
  File "C:\Users\EAL\Anaconda3\envs\testenv4\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\EAL\Documents\prototyping\torch-points3d\torch_points3d\modules\RandLANet\modules.py", line 123, in forward
    return self._conv.forward(data)
  File "C:\Users\EAL\Documents\prototyping\torch-points3d\torch_points3d\core\base_conv\message_passing.py", line 241, in forward
    x = self.features_downsample_nn(x)  # (N, outdim//4)
  File "C:\Users\EAL\Anaconda3\envs\testenv4\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\EAL\Anaconda3\envs\testenv4\lib\site-packages\torch\nn\modules\container.py", line 119, in forward
    input = module(input)
  File "C:\Users\EAL\Anaconda3\envs\testenv4\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\EAL\Anaconda3\envs\testenv4\lib\site-packages\torch\nn\modules\container.py", line 119, in forward
    input = module(input)
  File "C:\Users\EAL\Anaconda3\envs\testenv4\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\EAL\Anaconda3\envs\testenv4\lib\site-packages\torch\nn\modules\linear.py", line 94, in forward
    return F.linear(input, self.weight, self.bias)
  File "C:\Users\EAL\Anaconda3\envs\testenv4\lib\site-packages\torch\nn\functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 dim 1 must match mat2 dim 0
```

Thanks in advance for your feedback.

**Comment by nicolas-chaulet** [comment]
Hey! To be honest the whole module should probably be written again, we really haven't put any time into that. Starting there: `\RandLANet\modules.py` you can add the basic blocks that are required and then those modules are assembled into a unet architecture (based on the config yaml file) in the `models`segmentation/randlanet.py` file

**Comment by Stakhan** [comment]
Thanks for your reply and the starting points. I'll try to write it again in the upcoming weeks then!
