### ISSUE TITLE
ModuleNotFoundError in Unittest

### ISSUE THREAD

**Issue by loicland** [nicolas-chaulet/torch-points3d#273]
I am having a similar issue than #270 but for Linux, so I created a new issue.
ubuntu 18.04, python 3.7, cuda 10.1, pytorch 1.4

Poetry install everything, but unittest fails.

```ERROR:root:The testing module requires faiss. You can install the GPU version with the command 'conda install faiss-gpu -c pytorch or the CPU version with 'conda install faiss-cpu -c pytorch'. Learn more at https://github.com/facebookresearch/faiss/blob/master/INSTALL.md```

Eventhough I installed faiss. From `conda list`
``` faiss-cpu                 1.6.3            py37h6bb024c_0    pytorch ```

Then 
```
test_kpconv (test.test_api.TestAPIEncoder) ... ERROR
test_pn2 (test.test_api.TestAPIEncoder) ... ERROR
test_rsconv (test.test_api.TestAPIEncoder) ... ERROR
test_kpconv (test.test_api.TestAPIUnet) ... ERROR
test_pn2 (test.test_api.TestAPIUnet) ... ERROR
test_rsconv (test.test_api.TestAPIUnet) ... ERROR
...
test_accumulated_gradient (test.test_basemodel.TestSimpleBatch) ... ERROR
...
test.test_ind_tracker (unittest.loader._FailedTest) ... ERROR
test.test_interpolateop (unittest.loader._FailedTest) ... ERROR
test.test_kpconv (unittest.loader._FailedTest) ... ERROR
test.test_losses (unittest.loader._FailedTest) ... ERROR
...
test_model_ckpt_using_pointnet2ms (test.test_model_checkpoint.TestModelCheckpoint) ... ERROR
test_createall (test.test_models.TestModelUtils) ... /home/ign.fr/llandrieu/Documents/code/torch-points3d/test/../torch_points3d/utils/model_building_utils/resolver_utils.py:11: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if isinstance(v, collections.MutableMapping):
test_largekpconv (test.test_models.TestModelUtils) ... ERROR
test_pointnet2ms (test.test_models.TestModelUtils) ... ERROR
...
test_siamese_minkowski (test.test_models.TestModelUtils) ... ERROR
...
torch_points3d.core.spatial_ops (unittest.loader._FailedTest) ... ERROR
torch_points3d.modules.KPConv (unittest.loader._FailedTest) ... ERROR
torch_points3d.modules.MinkowskiEngine (unittest.loader._FailedTest) ... ERROR
torch_points3d.modules.PointCNN (unittest.loader._FailedTest) ... ERROR
torch_points3d.modules.RSConv (unittest.loader._FailedTest) ... ERROR
torch_points3d.modules.RandLANet (unittest.loader._FailedTest) ... ERROR
torch_points3d.modules.pointnet2 (unittest.loader._FailedTest) ... ERROR
```

the rest passes.

Detailed error:
```
======================================================================
ERROR: test_kpconv (test.test_api.TestAPIEncoder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ign.fr/llandrieu/Documents/code/torch-points3d/test/test_api.py", line 134, in test_kpconv
    from torch_points3d.applications.kpconv import KPConv
  File "/home/ign.fr/llandrieu/Documents/code/torch-points3d/test/../torch_points3d/applications/kpconv.py", line 7, in <module>
    from torch_points3d.modules.KPConv import *
  File "/home/ign.fr/llandrieu/Documents/code/torch-points3d/test/../torch_points3d/modules/KPConv/__init__.py", line 1, in <module>
    from .blocks import *
  File "/home/ign.fr/llandrieu/Documents/code/torch-points3d/test/../torch_points3d/modules/KPConv/blocks.py", line 7, in <module>
    from torch_points3d.core.spatial_ops import RadiusNeighbourFinder
  File "/home/ign.fr/llandrieu/Documents/code/torch-points3d/test/../torch_points3d/core/spatial_ops/__init__.py", line 1, in <module>
    from .neighbour_finder import *
  File "/home/ign.fr/llandrieu/Documents/code/torch-points3d/test/../torch_points3d/core/spatial_ops/neighbour_finder.py", line 5, in <module>
    import torch_points_kernels as tp
  File "/home/ign.fr/llandrieu/.cache/pypoetry/virtualenvs/torch-points3d-5mIvvJJ2-py3.7/lib/python3.7/site-packages/torch_points_kernels/__init__.py", line 1, in <module>
    from .torchpoints import *
  File "/home/ign.fr/llandrieu/.cache/pypoetry/virtualenvs/torch-points3d-5mIvvJJ2-py3.7/lib/python3.7/site-packages/torch_points_kernels/torchpoints.py", line 7, in <module>
    import torch_points_kernels.points_cpu as tpcpu
ModuleNotFoundError: No module named 'torch_points_kernels.points_cpu'
```

**Comment by nicolas-chaulet** [comment]
Hi @loicland thanks for reporting. Looks like torch-points-kernels did not install correctly. What happens if you install torch-points-kernels "manually"?
```
poetry run pip install torch-points-kernels --no-cache -v
```

**Comment by loicland** [comment]
``` (base) (torch-points3d-5mIvvJJ2-py3.7) llandrieu@DEL1912W001:~/Documents/code/torch-points3d$ poetry run pip install torch-points-kernels --no-cache -v ```

gives

```
Created temporary directory: /tmp/pip-ephem-wheel-cache-zdm9tg4l
Created temporary directory: /tmp/pip-req-tracker-xz3cl4da
Created requirements tracker '/tmp/pip-req-tracker-xz3cl4da'
Created temporary directory: /tmp/pip-install-idyz8i3u
Requirement already satisfied: torch-points-kernels in /home/ign.fr/llandrieu/.cache/pypoetry/virtualenvs/torch-points3d-5mIvvJJ2-py3.7/lib/python3.7/site-packages (0.6.1)
Requirement already satisfied: torch>=1.1.0 in /home/ign.fr/llandrieu/.cache/pypoetry/virtualenvs/torch-points3d-5mIvvJJ2-py3.7/lib/python3.7/site-packages (from torch-points-kernels) (1.3.1)
Requirement already satisfied: numpy in /home/ign.fr/llandrieu/.cache/pypoetry/virtualenvs/torch-points3d-5mIvvJJ2-py3.7/lib/python3.7/site-packages (from torch>=1.1.0->torch-points-kernels) (1.18.4)
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-xz3cl4da'
1 location(s) to search for versions of pip:
* https://pypi.org/simple/pip/
Getting page https://pypi.org/simple/pip/
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/pip/ HTTP/1.1" 200 13422
Analyzing links from page https://pypi.org/simple/pip/
  Found link https://files.pythonhosted.org/packages/3d/9d/1e313763bdfb6a48977b65829c6ce2a43eaae29ea2f907c8bbef024a7219/pip-0.2.tar.gz#sha256=88bb8d029e1bf4acd0e04d300104b7440086f94cc1ce1c5c3c31e3293aee1f81 (from https://pypi.org/simple/pip/), version: 0.2
  Found link https://files.pythonhosted.org/packages/18/ad/c0fe6cdfe1643a19ef027c7168572dac6283b80a384ddf21b75b921877da/pip-0.2.1.tar.gz#sha256=83522005c1266cc2de97e65072ff7554ac0f30ad369c3b02ff3a764b962048da (from https://pypi.org/simple/pip/), version: 0.2.1
  Found link https://files.pythonhosted.org/packages/17/05/f66144ef69b436d07f8eeeb28b7f77137f80de4bf60349ec6f0f9509e801/pip-0.3.tar.gz#sha256=183c72455cb7f8860ac1376f8c4f14d7f545aeab8ee7c22cd4caf79f35a2ed47 (from https://pypi.org/simple/pip/), version: 0.3
...
```

This doesn't seem to change the result of the unittest.

**Comment by nicolas-chaulet** [comment]
Sorry you will need to uninstall torch-points-kernels first
```
poetry run pip uninstall torch-points-kernels
poetry run pip install torch-points-kernels --no-cache -v
```

**Comment by loicland** [comment]
Still no luck!

```
torch-points3d-5mIvvJJ2-py3.7) (base) llandrieu@DEL1912W001:~/Documents/code/torch-points3d$ poetry run pip uninstall torch-points-kernels
Found existing installation: torch-points-kernels 0.6.1
Uninstalling torch-points-kernels-0.6.1:
  Would remove:
    /home/ign.fr/llandrieu/.cache/pypoetry/virtualenvs/torch-points3d-5mIvvJJ2-py3.7/lib/python3.7/site-packages/torch_points_kernels-0.6.1.dist-info/*
    /home/ign.fr/llandrieu/.cache/pypoetry/virtualenvs/torch-points3d-5mIvvJJ2-py3.7/lib/python3.7/site-packages/torch_points_kernels/*
Proceed (y/n)? y
  Successfully uninstalled torch-points-kernels-0.6.1
```
then
```
(torch-points3d-5mIvvJJ2-py3.7) (base) llandrieu@DEL1912W001:~/Documents/code/torch-points3d$ poetry run pip install torch-points-kernels --no-cache -v
Non-user install because user site-packages disabled
Created temporary directory: /tmp/pip-ephem-wheel-cache-cw8tid53
Created temporary directory: /tmp/pip-req-tracker-c4oy8j4p
Initialized build tracking at /tmp/pip-req-tracker-c4oy8j4p
Created build tracker: /tmp/pip-req-tracker-c4oy8j4p
Entered build tracker: /tmp/pip-req-tracker-c4oy8j4p
Created temporary directory: /tmp/pip-install-k5n6k1hr
1 location(s) to search for versions of torch-points-kernels:
* https://pypi.org/simple/torch-points-kernels/
Fetching project page and analyzing links: https://pypi.org/simple/torch-points-kernels/
Getting page https://pypi.org/simple/torch-points-kernels/
Found index url https://pypi.org/simple
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/torch-points-kernels/ HTTP/1.1" 200 751
  Found link https://files.pythonhosted.org/packages/7d/78/6184c784765bb45c025ef6df5379ae9220faf89bbbd1a6fd79894de5b146/torch-points-kernels-0.5.0.tar.gz#sha256=3b8b378c77f7bd0bf20e140eb4dd64f682adb890e49bfd5b91d042380129fc22 (from https://pypi.org/simple/torch-points-kernels/), version: 0.5.0
  Found link https://files.pythonhosted.org/packages/94/7b/48a12c3612f3bf9776ad64e00c7462e211cc28f94a3ff2140682aa9e56a2/torch-points-kernels-0.5.1.tar.gz#sha256=d8acf6e9eec6595ff783e63609e12b7ec58af6f12b36f20cddc4d82c2206f28b (from https://pypi.org/simple/torch-points-kernels/), version: 0.5.1
  Found link https://files.pythonhosted.org/packages/ae/bc/f952ed26d80f00a169f072c586dc8c71bd9878955289840d1a0efcfaa185/torch-points-kernels-0.5.2.tar.gz#sha256=c629adc36fc143d5d4e0e7a5eb734e282fdc59be73edebd433d2418061023bcd (from https://pypi.org/simple/torch-points-kernels/), version: 0.5.2
 ...
    Skipping link: unsupported archive format: .exe: https://files.pythonhosted.org/packages/0b/1b/2298438741c10969a34ea3523e8a009dccb4cbf9ed16ed6678eaf0043303/setuptools-0.6c7.win32-py2.3.exe#sha256=d31e38c38208ea025efab029bf4b22ebd74b37ec019c8b0743b9571a37d9c56d 
...
    Skipping link: unsupported archive format: .egg: https://files.pythonhosted.org/packages/8e/6b/c1cd58d373ce4d3c8d4cb61e2185c0b0ec58911eb742c0dca026ff1450ed/setuptools-0.6c8-py2.4.egg#sha256=ef3eebee06a96a0257567f311089363a873dce2b1cb616af4a2406ab2203dfab (from https://pypi.org/simple/setuptools/)
...
  Found link https://files.pythonhosted.org/packages/08/25/f204a6138dade2f6757b4ae99bc3994aac28a5602c97ddb2a35e0e22fbc4/pip-20.1.1.tar.gz#sha256=27f8dc29387dd83249e06e681ce087e6061826582198a425085e0bf4c1cf3a55 (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 20.1.1
Given no hashes to check 139 links for project 'pip': discarding no candidates
```
and then the unittest produces the same errors.

As of note, the folder `pypoetry/virtualenvs/torch-points3d-5mIvvJJ2-py3.7/lib/python3.7/site-packages/torch_points_kernels` only contains:
```__init__.py  knn.py  __pycache__  torchpoints.py```

i  don't know if it should contain more elements?

**Comment by nicolas-chaulet** [comment]
Yes it should contain a compiled library .so. Let me try on my end from
scratch

**Comment by nicolas-chaulet** [comment]
SO, I found the issue, it is with python 3.7 and torch-points-kernels. Would you mind trying python 3.6? I'll work on that in the meantime

**Comment by nicolas-chaulet** [comment]
@loicland this should be fixed now, if you could give it a go and close this if it is fixed that would be great!

**Comment by loicland** [comment]
works perfectly thanks!

**Comment by guochengqian** [comment]
Hi, I tried different env settings. I am only able to run `torch-points-kenels` at:
`python 3.6, Cuda 10.0, PyTorch 1.4`

envs below did not work for me (ubuntu 18.04):
python 3.6, Cuda 10.1, PyTorch 1.5
python 3.7, Cuda 10.1, PyTorch 1.5

but if one does not need torch-points-kennels (dense farthest  point sampling) cuda10.1 and PyTorch 1.5 work fine).
