### ISSUE TITLE
RuntimeError: class '__torch__.torch_sparse.storage.SparseStorage' already defined

### ISSUE THREAD

**Issue by loicland** [nicolas-chaulet/torch-points3d#287]
Hi,

thanks for the hard work. I ran `poetry install --no-root --no-dev` without issue, but I now get the following errors when launching the unittest (sorry for wall of text):
```
test.test_api (unittest.loader._FailedTest) ... ERROR
test.test_basedataset (unittest.loader._FailedTest) ... ERROR
test.test_basemodel (unittest.loader._FailedTest) ... ERROR
test.test_batch (unittest.loader._FailedTest) ... ERROR
test_scheduler (test.test_bn_scheduler.TestBNMomentumScheduler) ... ok
test_getCount (test.test_confusionMatrix.TestConfusionMatrix) ... ok
test_getIoU (test.test_confusionMatrix.TestConfusionMatrix) ... ok
test_getIoUMissing (test.test_confusionMatrix.TestConfusionMatrix) ... ok
test_getMeanIoU (test.test_confusionMatrix.TestConfusionMatrix) ... ok
test_test_getMeanIoUMissing (test.test_confusionMatrix.TestConfusionMatrix) ... ok
test.test_dataset_factory (unittest.loader._FailedTest) ... ERROR
test.test_filter (unittest.loader._FailedTest) ... ERROR
test.test_fps (unittest.loader._FailedTest) ... ERROR
test.test_grid_sampling (unittest.loader._FailedTest) ... ERROR
test.test_ind_tracker (unittest.loader._FailedTest) ... ERROR
test.test_interpolateop (unittest.loader._FailedTest) ... ERROR
test.test_kpconv (unittest.loader._FailedTest) ... ERROR
test.test_losses (unittest.loader._FailedTest) ... ERROR
test.test_lr_scheduler (unittest.loader._FailedTest) ... ERROR
test.test_make_pair (unittest.loader._FailedTest) ... ERROR
test.test_model_checkpoint (unittest.loader._FailedTest) ... ERROR
test.test_models (unittest.loader._FailedTest) ... ERROR
test.test_modules (unittest.loader._FailedTest) ... ERROR
test.test_msdata (unittest.loader._FailedTest) ... ERROR
test.test_msdatapair (unittest.loader._FailedTest) ... ERROR
test.test_normal (unittest.loader._FailedTest) ... ERROR
test.test_random_sphere (unittest.loader._FailedTest) ... ERROR
test.test_registration_metrics (unittest.loader._FailedTest) ... ERROR
test.test_registration_tracker (unittest.loader._FailedTest) ... ERROR
test.test_resolver (unittest.loader._FailedTest) ... ERROR
test.test_sampler (unittest.loader._FailedTest) ... ERROR
test_simple (test.test_samplers.TestBalancedRandomSampler) ... ok
test.test_sampling_strategy (unittest.loader._FailedTest) ... ERROR
test.test_segmentationtracker (unittest.loader._FailedTest) ... ERROR
test.test_shapenetforward (unittest.loader._FailedTest) ... ERROR
test_track (test.test_shapenetparttracker.TestSegmentationTracker) ... ok
test.test_sphere_sampling (unittest.loader._FailedTest) ... ERROR
test.test_to_sparse (unittest.loader._FailedTest) ... ERROR
test.test_transform (unittest.loader._FailedTest) ... ERROR
test.test_unwrapped_unet_base (unittest.loader._FailedTest) ... ERROR
test.test_visualization (unittest.loader._FailedTest) ... ERROR
torch_points3d.core.data_transform (unittest.loader._FailedTest) ... ERROR
torch_points3d.core.losses (unittest.loader._FailedTest) ... ERROR
torch_points3d.core.spatial_ops (unittest.loader._FailedTest) ... ERROR
torch_points3d.datasets.segmentation (unittest.loader._FailedTest) ... ERROR
torch_points3d.models.base_architectures (unittest.loader._FailedTest) ... ERROR
torch_points3d.modules.KPConv (unittest.loader._FailedTest) ... ERROR
torch_points3d.modules.MinkowskiEngine (unittest.loader._FailedTest) ... ERROR
torch_points3d.modules.PointCNN (unittest.loader._FailedTest) ... ERROR
torch_points3d.modules.PointNet (unittest.loader._FailedTest) ... ERROR
torch_points3d.modules.RSConv (unittest.loader._FailedTest) ... ERROR
torch_points3d.modules.RandLANet (unittest.loader._FailedTest) ... ERROR
torch_points3d.modules.pointnet2 (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test.test_api (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.test_api
Traceback (most recent call last):
  File "/home/il/landril/scratch/conda/envs/myenv/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/il/landril/scratch/conda/envs/myenv/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/il/landril/Documents/code/torch-points3d/test/test_api.py", line 9, in <module>
    from test.mockdatasets import MockDatasetGeometric, MockDataset
  File "/home/il/landril/Documents/code/torch-points3d/test/mockdatasets.py", line 2, in <module>
    from torch_geometric.data import Data, Batch
  File "/home/il/landril/.cache/pypoetry/virtualenvs/torch-points3d-4VIqQfrn-py3.6/lib/python3.6/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/il/landril/.cache/pypoetry/virtualenvs/torch-points3d-4VIqQfrn-py3.6/lib/python3.6/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/il/landril/.cache/pypoetry/virtualenvs/torch-points3d-4VIqQfrn-py3.6/lib/python3.6/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/home/il/landril/.cache/pypoetry/virtualenvs/torch-points3d-4VIqQfrn-py3.6/lib/python3.6/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/il/landril/.cache/pypoetry/virtualenvs/torch-points3d-4VIqQfrn-py3.6/lib/python3.6/site-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce
  File "/home/il/landril/.cache/pypoetry/virtualenvs/torch-points3d-4VIqQfrn-py3.6/lib/python3.6/site-packages/torch_sparse/__init__.py", line 34, in <module>
    from .storage import SparseStorage  # noqa
  File "/home/il/landril/.cache/pypoetry/virtualenvs/torch-points3d-4VIqQfrn-py3.6/lib/python3.6/site-packages/torch_sparse/storage.py", line 21, in <module>
    class SparseStorage(object):
  File "/home/il/landril/.cache/pypoetry/virtualenvs/torch-points3d-4VIqQfrn-py3.6/lib/python3.6/site-packages/torch/jit/__init__.py", line 1274, in script
    _compile_and_register_class(obj, _rcb, qualified_name)
  File "/home/il/landril/.cache/pypoetry/virtualenvs/torch-points3d-4VIqQfrn-py3.6/lib/python3.6/site-packages/torch/jit/__init__.py", line 1115, in _compile_and_register_class
    _jit_script_class_compile(qualified_name, ast, rcb)
RuntimeError: 
__init__(__torch__.torch_sparse.storage.SparseStorage self, Tensor? row, Tensor? rowptr, Tensor? col, Tensor? value, (int, int)? sparse_sizes, Tensor? rowcount, Tensor? colptr, Tensor? colcount, Tensor? csr2csc, Tensor? csc2csr, bool is_sorted) -> (None):
Expected a value of type 'Optional[Tensor]' for argument 'row' but instead found type 'int'.
:
  File "/home/il/landril/.cache/pypoetry/virtualenvs/torch-points3d-4VIqQfrn-py3.6/lib/python3.6/site-packages/torch_sparse/storage.py", line 283
        col = idx % num_cols

        return SparseStorage(row=row, rowptr=None, col=col, value=self._value,
               ~~~~~~~~~~~~~ <--- HERE
                             sparse_sizes=(num_rows, num_cols), rowcount=None,
                             colptr=None, colcount=None, csr2csc=None,
```
and I also get the following error a lot:
```
======================================================================
ERROR: test.test_basedataset (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.test_basedataset
Traceback (most recent call last):
  File "/home/il/landril/scratch/conda/envs/myenv/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/il/landril/scratch/conda/envs/myenv/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/il/landril/Documents/code/torch-points3d/test/test_basedataset.py", line 8, in <module>
    from torch_geometric.data.data import Data
  File "/home/il/landril/.cache/pypoetry/virtualenvs/torch-points3d-4VIqQfrn-py3.6/lib/python3.6/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/il/landril/.cache/pypoetry/virtualenvs/torch-points3d-4VIqQfrn-py3.6/lib/python3.6/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/il/landril/.cache/pypoetry/virtualenvs/torch-points3d-4VIqQfrn-py3.6/lib/python3.6/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/home/il/landril/.cache/pypoetry/virtualenvs/torch-points3d-4VIqQfrn-py3.6/lib/python3.6/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/il/landril/.cache/pypoetry/virtualenvs/torch-points3d-4VIqQfrn-py3.6/lib/python3.6/site-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce
  File "/home/il/landril/.cache/pypoetry/virtualenvs/torch-points3d-4VIqQfrn-py3.6/lib/python3.6/site-packages/torch_sparse/__init__.py", line 34, in <module>
    from .storage import SparseStorage  # noqa
  File "/home/il/landril/.cache/pypoetry/virtualenvs/torch-points3d-4VIqQfrn-py3.6/lib/python3.6/site-packages/torch_sparse/storage.py", line 21, in <module>
    class SparseStorage(object):
  File "/home/il/landril/.cache/pypoetry/virtualenvs/torch-points3d-4VIqQfrn-py3.6/lib/python3.6/site-packages/torch/jit/__init__.py", line 1274, in script
    _compile_and_register_class(obj, _rcb, qualified_name)
  File "/home/il/landril/.cache/pypoetry/virtualenvs/torch-points3d-4VIqQfrn-py3.6/lib/python3.6/site-packages/torch/jit/__init__.py", line 1115, in _compile_and_register_class
    _jit_script_class_compile(qualified_name, ast, rcb)
RuntimeError: class '__torch__.torch_sparse.storage.SparseStorage' already defined. (register_type at /pytorch/torch/csrc/jit/script/compilation_unit.h:167)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x2ae15c61d193 in /home/il/landril/.cache/pypoetry/virtualenvs/torch-points3d-4VIqQfrn-py3.6/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x78d979 (0x2ae110fbd979 in /home/il/landril/.cache/pypoetry/virtualenvs/torch-points3d-4VIqQfrn-py3.6/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #2: <unknown function> + 0x774dee (0x2ae110fa4dee in /home/il/landril/.cache/pypoetry/virtualenvs/torch-points3d-4VIqQfrn-py3.6/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x775c37 (0x2ae110fa5c37 in /home/il/landril/.cache/pypoetry/virtualenvs/torch-points3d-4VIqQfrn-py3.6/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x2961c4 (0x2ae110ac61c4 in /home/il/landril/.cache/pypoetry/virtualenvs/torch-points3d-4VIqQfrn-py3.6/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
```
What worries me the most is that it ends in a segfault
```
----------------------------------------------------------------------
Ran 53 tests in 0.107s

FAILED (errors=45)
Segmentation fault (core dumped)
```

I run CUDA10.1 and torch==1.4.0.

Thanks!

**Comment by loicland** [comment]
reinstalled torch_sparse from the wheels directly, I have now a different error. Opening another issue.
