### ISSUE TITLE
ModuleNotFoundError: No module named 'torch_points3d.models.D:\\AI\\TorchPoints3D\\torch-points3d\\test\\'

### ISSUE THREAD

**Issue by MBrandt-NASA** [nicolas-chaulet/torch-points3d#419]
Hi, thanks for creating this incredible 3d point cloud DL library!! 😄 

I have a mostly working install: Windows 10, python 3.7.4, pytorch 1.6, and all requirements installed correctly (including torch-points-kernels), as far as I can tell.

Out of 152 tests, 43 failed.  I haven't installed the Minkowski stuff yet.  

Many of my errors are of the form:

`ModuleNotFoundError: No module named 'torch_points3d.models.D:\\AI\\TorchPoints3D\\torch-points3d\\test\\'`

==================

Example:

```
ERROR: test_runall (test.test_models.TestModels) [pointnet2]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\AI\TorchPoints3D\torch-points3d\test\test_models.py", line 127, in test_runall
    model = instantiate_model(models_config, dataset)
  File "D:\AI\TorchPoints3D\torch-points3d\torch_points3d\models\model_factory.py", line 30, in instantiate_model
    modellib = importlib.import_module(model_module)
  File "C:\Users\mabrandt\AppData\Local\Continuum\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'torch_points3d.models.D:\\AI\\TorchPoints3D\\torch-points3d\\test\\'
```

Any ideas?

Thanks very much for any thoughts.  😃

**Comment by MBrandt-NASA** [comment]
Ok I found the problem!  😄 --
line 117 in test_models.py:

`associated_task = type_file.split("/")[-2]`

It should be using os.path.split() somehow... I will figure that out and submit a fix when/if I have time.  The Windows path that has "\\" made this fail.  😉

**Comment by MBrandt-NASA** [comment]
Ok, this line of code (i.e. replacing line 117 in test_models.py) appears to fix all issues for Windows 10:

`associated_task = os.path.normpath(type_file).split(os.path.sep)[-2]`

Now I only get 22 errors from unittests, most of which since I haven't installed 'MinkowskiEngine' yet.

**Comment by humanpose1** [comment]
Hi,

Nice catch !!! Thanks for having detecting this problem :). Can you please make a PR to fix it ?
