### ISSUE TITLE
Problem of using pretrained model in demo_registration_3dm.ipynb.

### ISSUE THREAD

**Issue by ybbbbt** [nicolas-chaulet/torch-points3d#422]
Hi, Thanks for building such a useful library.

I try to run the notebook in `notebooks/demo_registration_3dm.ipynb`, but when I run to the line:
 `model = PretainedRegistry.from_pretrained("minkowski-registration-3dmatch").cuda()`, 
I got the error like that :

```
WARNING: skipping download of existing file /home/abc/anaconda3/envs/hf/lib/python3.7/site-packages/torch_points3d/applications/weights/minkowski-registration-3dmatch.pt
Error trying to create train_transform, [{'transform': 'SaveOriginalPosId'}, {'transform': 'FixedPoints', 'lparams': [20000]}, {'transform': 'RandomNoise', 'params': {'sigma': 0.005, 'clip': 0.05}}, {'transform': 'RandomRotate', 'params': {'degrees': 180, 'axis': 0}}, {'transform': 'RandomRotate', 'params': {'degrees': 180, 'axis': 1}}, {'transform': 'RandomRotate', 'params': {'degrees': 180, 'axis': 2}}, {'transform': 'RandomScaleAnisotropic', 'params': {'scales': [0.9, 1.2]}}, {'transform': 'XYZFeature', 'params': {'add_x': True, 'add_y': True, 'add_z': True}}, {'transform': 'GridSampling', 'params': {'size': '${data.first_subsampling}', 'quantize_coords': True, 'mode': 'last'}}, {'transform': 'AddOnes'}, {'transform': 'AddFeatByKey', 'params': {'add_to_x': True, 'feat_name': 'ones'}}, {'transform': 'Jitter'}]
Traceback (most recent call last):
  File "/home/abc/anaconda3/envs/hf/lib/python3.7/site-packages/torch_points3d/datasets/base_dataset.py", line 125, in set_transform
    transform = instantiate_transforms(getattr(dataset_opt, key_name))
  File "/home/abc/anaconda3/envs/hf/lib/python3.7/site-packages/torch_points3d/core/data_transform/__init__.py", line 86, in instantiate_transforms
    transforms.append(instantiate_transform(transform))
  File "/home/abc/anaconda3/envs/hf/lib/python3.7/site-packages/torch_points3d/core/data_transform/__init__.py", line 69, in instantiate_transform
    return cls(**tr_params)
TypeError: __init__() got an unexpected keyword argument 'quantize_coords'
Error trying to create test_transform, [{'transform': 'SaveOriginalPosId'}, {'transform': 'FixedPoints', 'lparams': [20000]}, {'transform': 'RandomRotate', 'params': {'degrees': 180, 'axis': 0}}, {'transform': 'RandomRotate', 'params': {'degrees': 180, 'axis': 1}}, {'transform': 'RandomRotate', 'params': {'degrees': 180, 'axis': 2}}, {'transform': 'XYZFeature', 'params': {'add_x': True, 'add_y': True, 'add_z': True}}, {'transform': 'GridSampling', 'params': {'size': '${data.first_subsampling}', 'quantize_coords': True, 'mode': 'last'}}, {'transform': 'AddOnes'}, {'transform': 'AddFeatByKey', 'params': {'add_to_x': True, 'feat_name': 'ones'}}]
Traceback (most recent call last):
  File "/home/abc/anaconda3/envs/hf/lib/python3.7/site-packages/torch_points3d/datasets/base_dataset.py", line 125, in set_transform
    transform = instantiate_transforms(getattr(dataset_opt, key_name))
  File "/home/abc/anaconda3/envs/hf/lib/python3.7/site-packages/torch_points3d/core/data_transform/__init__.py", line 86, in instantiate_transforms
    transforms.append(instantiate_transform(transform))
  File "/home/abc/anaconda3/envs/hf/lib/python3.7/site-packages/torch_points3d/core/data_transform/__init__.py", line 69, in instantiate_transform
    return cls(**tr_params)
TypeError: __init__() got an unexpected keyword argument 'quantize_coords'
```

while the pretrained model in `notebooks/demo_registration_kitti.ipynb` works like a charm.
Is there a problem with the checkpoint? Or is there something wrong with my configuration?

**Comment by humanpose1** [comment]
Hi @ybbbbt,

Thanks for your interest in the framework.
Yes, it raises an error message because the model has saved an old transform  (tha's why the transform are defined manually). And because we have changed the transforms, it's not defined anymore.
But normally the model is working and it can compute features even if it raises this error message. We need to define the transforms manually as it is done in the notebook.

Best,
