### ISSUE TITLE
What command is needed to train KPConv semantic segmentation on S3DIS?

### ISSUE THREAD

**Issue by lwx-bupt** [nicolas-chaulet/torch-points3d#439]
I tried
python train.py task=segmentation model_type=kpconv model_name=kpconv dataset=s3dis
but it says
hydra.errors.MissingConfigException: Could not load data/segmentation/s3dis.yaml
So what needed to be modified?

**Comment by tchaton** [comment]
Hey @lwx-bupt,

You model_name and dataset are wrong :)

model_name should be a modelName within kpconv.yaml file like KPConvPaper and dataset should be a dataset yawl file.

```
python train.py task=segmentation model_type=kpconv model_name=KPConvPaper dataset=s3disfused training=s3dis_benchmark/kpconv```

You can see some old trainings there: https://wandb.ai/nicolas/s3dis-benchmark?workspace=user-thomas-chaton

Best,
T.C

**Comment by lwx-bupt** [comment]
Okay. Thanks for your information

**Comment by lwx-bupt** [comment]
Hi
I've started training with the command
> python train.py task=segmentation model_type=kpconv model_name=KPConvPaper dataset=s3disfused training=kpconv
but the terminal shows:
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    main()
  File "/root/torch-points3d/pcb/lib/python3.6/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
  File "/root/torch-points3d/pcb/lib/python3.6/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "/root/torch-points3d/pcb/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 86, in run
    job_subdir_key=None,
  File "/root/torch-points3d/pcb/lib/python3.6/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "train.py", line 13, in main
    trainer.train()
  File "/root/torch-points3d/torch_points3d/trainer.py", line 136, in train
    self._train_epoch(epoch)
  File "/root/torch-points3d/torch_points3d/trainer.py", line 186, in _train_epoch
    for i, data in enumerate(tq_train_loader):
  File "/root/torch-points3d/pcb/lib/python3.6/site-packages/tqdm/std.py", line 1130, in __iter__
    for obj in iterable:
  File "/root/torch-points3d/pcb/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/root/torch-points3d/pcb/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/root/torch-points3d/pcb/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/root/torch-points3d/pcb/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/torch-points3d/pcb/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/torch-points3d/pcb/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/root/torch-points3d/torch_points3d/datasets/batch.py", line 48, in from_data_list
    batch[key] = torch.stack(batch[key])
RuntimeError: stack expects each tensor to be equal size, but got [18261, 4] at entry 0 and [14425, 4] at entry 1
removing "training=kpconv"
