### ISSUE TITLE
Panoptic pointgroup training on S3DISfused dataset

### ISSUE THREAD

**Issue by fengziyue** [nicolas-chaulet/torch-points3d#452]
Dear sir, I'm trying to train panoptic pointgroup on s3dis dataset by this command:
`poetry run python train.py task=panoptic model_type=pointgroup model_name=PointGroup dataset=s3disfused`

but encountered several errors:

(1), S3DISFusedDataset doesn't have attribute grid_size

(2), S3DISFusedDataset doesn't have stuff_classes

(3), batch object (data) doesn't have attribute "coords":
`File "train.py", line 13, in main
    trainer.train()
  File "/home/zfeng/torch-points3d-master/torch_points3d/trainer.py", line 136, in train                         
    self._train_epoch(epoch)
  File "/home/zfeng/torch-points3d-master/torch_points3d/trainer.py", line 190, in _train_epoch                  
    self._model.optimize_parameters(epoch, self._dataset.batch_size)
  File "/home/zfeng/torch-points3d-master/torch_points3d/models/base_model.py", line 196, in optimize_parameters 
    self.forward(epoch=epoch)  # first call forward to calculate intermediate results                            
  File "/home/zfeng/torch-points3d-master/torch_points3d/models/panoptic/pointgroup.py", line 72, in forward     
    backbone_features = self.Backbone(self.input).x
  File "/home/zfeng/.conda/envs/torchp3d/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zfeng/torch-points3d-master/torch_points3d/applications/minkowski.py", line 178, in forward        
    self._set_input(data)
  File "/home/zfeng/torch-points3d-master/torch_points3d/applications/minkowski.py", line 119, in _set_input     
    coords = torch.cat([data.batch.unsqueeze(-1).int(), data.coords.int()], -1)                                  
AttributeError: 'Batch' object has no attribute 'coords'`

Could you give me any advice?

**Comment by fengziyue** [comment]
@tchaton

**Comment by nicolas-chaulet** [comment]
Right :) Looks like we haven't finished implementing it properly... I just pushed some code changes to master, could you update the repo and let me know?

**Comment by nicolas-chaulet** [comment]
Hey @fengziyue did you get a chance to try that out?

**Comment by fengziyue** [comment]
@nicolas-chaulet 
It runs, but get this warning:
`points3d/torch_points3d/datasets/panoptic/utils.py:33: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor)`
so I change the corresponding code from:
`centers.append(torch.tensor(center))`
to:
`centers.append(center.clone().detach())`
Is that correct?

**Comment by fengziyue** [comment]
@nicolas-chaulet 
After that, I got another error:
`.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x151cc82c48d0>>
Traceback (most recent call last):
  File "/home/zfeng/.conda/envs/torchp3d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1101, in __del__
    self._shutdown_workers()
  File "/home/zfeng/.conda/envs/torchp3d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1075, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/home/zfeng/.conda/envs/torchp3d/lib/python3.6/multiprocessing/process.py", line 122, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
Exception ignored in: <bound method _MultiProcessingDataLoaderIter.__del__ of <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x151cc8319a58>>
Traceback (most recent call last):
  File "/home/zfeng/.conda/envs/torchp3d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1101, in __del__
    self._shutdown_workers()
  File "/home/zfeng/.conda/envs/torchp3d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1075, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/home/zfeng/.conda/envs/torchp3d/lib/python3.6/multiprocessing/process.py", line 122, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'`


 And the training crash every time in epoch3:
`0%|                                                                                                             | 0/105 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    main()
  File "/home/zfeng/.conda/envs/torchp3d/lib/python3.6/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
  File "/home/zfeng/.conda/envs/torchp3d/lib/python3.6/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "/home/zfeng/.conda/envs/torchp3d/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 86, in run
    job_subdir_key=None,
  File "/home/zfeng/.conda/envs/torchp3d/lib/python3.6/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "train.py", line 13, in main
    trainer.train()
  File "/home/zfeng/torch-points3d/torch_points3d/trainer.py", line 152, in train
    self._test_epoch(epoch, "test")
  File "/home/zfeng/torch-points3d/torch_points3d/trainer.py", line 244, in _test_epoch
    for data in tq_loader:
  File "/home/zfeng/.conda/envs/torchp3d/lib/python3.6/site-packages/tqdm/std.py", line 1174, in __iter__
    for obj in iterable:
  File "/home/zfeng/.conda/envs/torchp3d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 291, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/zfeng/.conda/envs/torchp3d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 737, in __init__
    w.start()
  File "/home/zfeng/.conda/envs/torchp3d/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/zfeng/.conda/envs/torchp3d/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/zfeng/.conda/envs/torchp3d/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/zfeng/.conda/envs/torchp3d/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/zfeng/.conda/envs/torchp3d/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory`

I have totally 372GB of RAM, it just used around 10GB of it, but crash every time. Do you have any idea about it?

**Comment by nicolas-chaulet** [comment]
humm that's frustrating... Could you try to decrease the num_workers parameter? Try maybe 1 and 0 just to see if that fixes the issue.

**Comment by nicolas-chaulet** [comment]
@fengziyue can you please confirm that this is fixed now?
