### ISSUE TITLE
No module named 'torch_points_kernels.points_cuda'

### ISSUE THREAD

**Issue by chenzhaiyu** [nicolas-chaulet/torch-points3d#456]
Hello, I ran into the error when importing any methods (RSConv, KPConv, PointNet2, VoteNet) from `torch_points3d.applications`. 

Error message:
```
Traceback (most recent call last):
...
  File ".../models/modelPCR.py", line 25, in <module>
    from torch_points3d.applications.rsconv import RSConv
  File ".../lib/site-packages/torch_points3d/applications/rsconv.py", line 8, in <module>
    from torch_points3d.modules.RSConv import *
  File ".../lib/site-packages/torch_points3d/modules/RSConv/__init__.py", line 1, in <module>
    from .dense import *
  File ".../lib/site-packages/torch_points3d/modules/RSConv/dense.py", line 8, in <module>
    import torch_points_kernels as tp
  File ".../lib/site-packages/torch_points_kernels/__init__.py", line 1, in <module>
    from .torchpoints import *
  File ".../lib/site-packages/torch_points_kernels/torchpoints.py", line 11, in <module>
    import torch_points_kernels.points_cuda as tpcuda
ModuleNotFoundError: No module named 'torch_points_kernels.points_cuda'
```

To reproduce:
```
from torch_points3d.applications.rsconv import RSConv
```

Env:
```
pytorch==1.4.0
torch-geometric==1.5.0
torch-points3d==1.1.1
```

Any hints? Thanks!

**Comment by nicolas-chaulet** [comment]
Hey @chenzhaiyu it is likely because torch_points_kernels did not compile properly with your CUDA device. Could you try to install it using some suggestions here:
https://github.com/nicolas-chaulet/torch-points-kernels/blob/master/README.md#troubleshooting

**Comment by nicolas-chaulet** [comment]
Stale for some time, closing now.
