### ISSUE TITLE
Recommended style of using the library?

### ISSUE THREAD

**Issue by chaitjo** [nicolas-chaulet/torch-points3d#509]
This might be a very basic Q about usage: What is the most efficient approach for re-producing results of various point cloud classification architectures on something simple like ModelNet? Should I be writing my own dataloaders, train and test functions, as in [the notebook here](https://github.com/nicolas-chaulet/torch-points3d/blob/master/notebooks/ObjectClassificationRSConv.ipynb) for RSConv, or should I follow [the README](https://github.com/nicolas-chaulet/torch-points3d#getting-started-train-pointnet-on-part-segmentation-task-for-dataset-shapenet), which suggests using the train.py API from the command line?

My example usage is that I'd like to design a new GNN-based approach, and towards that, the first thing I'd like to try is to fairly benchmark PointNet, DGCNN, etc. on ModelNet.

**Comment by nicolas-chaulet** [comment]
Hi @chaitjo I would suggest you clone the repo and use the train.py script. All the checkpointing, log tracking with wandb and wiring of models and datasets is handled for you in there. So unless you already have code for training it's probably the easiest. Let us know how it goes!

**Comment by chaitjo** [comment]
Thanks! Will do. 

Another quick Q: What is the difference between the models implemented in `torch_points3d/applications` and those in `torch_points3d/models`? (The documentation and README.md does not seem to have information about the applications module, but RSConv has been imported from it in the example notebook.)

**Comment by nicolas-chaulet** [comment]
The applications models are more or less the same as the `models` with the
difference that the models in `models` are often a bit custom in one way or
another. The applications models are some sort of stable and robust version
of the ones in models.

Le jeu. 3 déc. 2020 à 09:35, Chaitanya Joshi <notifications@github.com> a
écrit :

**Comment by chaitjo** [comment]
Hi @nicolas-chaulet, I am not sure if this deserves to be a separate issue, but here goes.

I followed your advise to work with the clones version of the repo and was able to follow along the tutorials, e.g. I could follow the example of training PointNet++ on ShapeNet segmentation. However, when I tried to repeat the same with SparseConv3d ResNet style models, I encountered errors:

```
(pointcloud) root@4GPU:/mnt/sdb/chaitanya/torch-points3d# python train.py task=segmentation model_type=sparseconv3d model_name=ResUNet32 dataset=shapenet_sparse
.
.
.
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    main()
  File "/home/chaitanya/miniconda3/envs/pointcloud/lib/python3.7/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
  File "/home/chaitanya/miniconda3/envs/pointcloud/lib/python3.7/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "/home/chaitanya/miniconda3/envs/pointcloud/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 86, in run
    job_subdir_key=None,
  File "/home/chaitanya/miniconda3/envs/pointcloud/lib/python3.7/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "train.py", line 13, in main
    trainer.train()
  File "/mnt/sdb/chaitanya/torch-points3d/torch_points3d/trainer.py", line 140, in train
    self._train_epoch(epoch)
  File "/mnt/sdb/chaitanya/torch-points3d/torch_points3d/trainer.py", line 194, in _train_epoch
    self._model.optimize_parameters(epoch, self._dataset.batch_size)
  File "/mnt/sdb/chaitanya/torch-points3d/torch_points3d/models/base_model.py", line 215, in optimize_parameters
    self.forward(epoch=epoch)  # first call forward to calculate intermediate results
  File "/mnt/sdb/chaitanya/torch-points3d/torch_points3d/models/segmentation/sparseconv3d.py", line 33, in forward
    features = self.backbone(self.input).x
  File "/home/chaitanya/miniconda3/envs/pointcloud/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/sdb/chaitanya/torch-points3d/torch_points3d/applications/sparseconv3d.py", line 190, in forward
    self._set_input(data)
  File "/mnt/sdb/chaitanya/torch-points3d/torch_points3d/applications/sparseconv3d.py", line 133, in _set_input
    self.input = sp3d.nn.SparseTensor(data.x, data.coords, data.batch, self.device)
AttributeError: 'Batch' object has no attribute 'coords'
```

I had previously obtained the same error message when attempting to use SparseConv3d for ModelNet classification by modifying the example notebook I pointed to previously (where I imported and built the SparseConv3d encoder from torch_points3d.applications in the same fashion as the RSConv example).

Am I using the wrong config files/dataset transforms here?
