### ISSUE TITLE
Issues using sparse convolutions

### ISSUE THREAD

**Issue by chaitjo** [nicolas-chaulet/torch-points3d#517]
I am logging a new issue based on #509 and updating it based on some new errors as I attempted to fix it: 

I followed the advise to work with the cloned version of the repo and was able to follow along the tutorials, e.g. I could follow the example of training PointNet++ on ShapeNet segmentation. However, when I tried to repeat the same with SparseConv3d ResNet style models, I encountered errors:

```
(pointcloud) root@4GPU:/mnt/sdb/chaitanya/torch-points3d# python train.py task=segmentation model_type=sparseconv3d model_name=ResUNet32 dataset=shapenet_sparse
.
.
.
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    main()
  File "/home/chaitanya/miniconda3/envs/pointcloud/lib/python3.7/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
  File "/home/chaitanya/miniconda3/envs/pointcloud/lib/python3.7/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "/home/chaitanya/miniconda3/envs/pointcloud/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 86, in run
    job_subdir_key=None,
  File "/home/chaitanya/miniconda3/envs/pointcloud/lib/python3.7/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "train.py", line 13, in main
    trainer.train()
  File "/mnt/sdb/chaitanya/torch-points3d/torch_points3d/trainer.py", line 140, in train
    self._train_epoch(epoch)
  File "/mnt/sdb/chaitanya/torch-points3d/torch_points3d/trainer.py", line 194, in _train_epoch
    self._model.optimize_parameters(epoch, self._dataset.batch_size)
  File "/mnt/sdb/chaitanya/torch-points3d/torch_points3d/models/base_model.py", line 215, in optimize_parameters
    self.forward(epoch=epoch)  # first call forward to calculate intermediate results
  File "/mnt/sdb/chaitanya/torch-points3d/torch_points3d/models/segmentation/sparseconv3d.py", line 33, in forward
    features = self.backbone(self.input).x
  File "/home/chaitanya/miniconda3/envs/pointcloud/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/sdb/chaitanya/torch-points3d/torch_points3d/applications/sparseconv3d.py", line 190, in forward
    self._set_input(data)
  File "/mnt/sdb/chaitanya/torch-points3d/torch_points3d/applications/sparseconv3d.py", line 133, in _set_input
    self.input = sp3d.nn.SparseTensor(data.x, data.coords, data.batch, self.device)
AttributeError: 'Batch' object has no attribute 'coords'
```

I had previously obtained the same error message when attempting to use SparseConv3d for ModelNet classification by modifying the example notebook I pointed to previously (where I imported and built the SparseConv3d encoder from torch_points3d.applications in the same fashion as the RSConv example).

Am I using the wrong config files/dataset transforms here?

(Note that both Minkowski engine and torchsparse are installed in my python environment.)

**Comment by chaitjo** [comment]
To ovrecome the above error, I realized that the GridSampling3D has no parameter named `grid_size` as in the config file `shapenet_sparse.yaml`. I updated `shapenet_sparse.yaml` to replace `grid_size` with `size` (which is the correct parameter for GridSampling3d:
```
data:
  class: shapenet.ShapeNetDataset
  dataset_name: "shapenet_sparse"
  task: segmentation
  dataroot: data
  normal: True
  use_category: True
  grid_size: 0.02
  pre_transforms:
    - transform: NormalizeScale
  train_transforms:
    - transform: RandomNoise
      params:
        sigma: 0.01
        clip: 0.05
    - transform: GridSampling3D
      params:
        **size: ${data.grid_size}**
        mode: "mean"
        quantize_coords: True
  test_transforms:
    - transform: GridSampling3D
      params:
        **size: ${data.grid_size}**
        quantize_coords: True
        mode: "mean"
  val_transforms:
    - transform: GridSampling3D
      params:
        **size: ${data.grid_size}**
        quantize_coords: True
        mode: "mean"
```

However, I now encounter new errors:
```
(pointcloud) root@4GPU:/mnt/sdb/chaitanya/torch-points3d# python train.py task=segmentation model_type=sparseconv3d model_name=ResUNet32 dataset=shapenet_sparse
.
.
.
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    main()
  File "/home/chaitanya/miniconda3/envs/pointcloud/lib/python3.7/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
  File "/home/chaitanya/miniconda3/envs/pointcloud/lib/python3.7/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "/home/chaitanya/miniconda3/envs/pointcloud/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 86, in run
    job_subdir_key=None,
  File "/home/chaitanya/miniconda3/envs/pointcloud/lib/python3.7/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "train.py", line 13, in main
    trainer.train()
  File "/mnt/sdb/chaitanya/torch-points3d/torch_points3d/trainer.py", line 140, in train
    self._train_epoch(epoch)
  File "/mnt/sdb/chaitanya/torch-points3d/torch_points3d/trainer.py", line 197, in _train_epoch
    self._tracker.track(self._model, data=data, **self.tracker_options)
  File "/mnt/sdb/chaitanya/torch-points3d/torch_points3d/metrics/shapenet_part_tracker.py", line 58, in track
    raise ValueError("Your model need to set the batch_idx variable in its set_input function.")
ValueError: Your model need to set the batch_idx variable in its set_input function.
```

I believe I am following the instructions for the library correctly, so I am not sure how to fix this. Could you please assist me here?

Additionally, is there any reference notebook/benchmark/script that you can point me to as reference for a fully functional sparse voxel-based convnet model?

**Comment by chaitjo** [comment]
I have momentarily been able to train the sparse convolution model by doing the following: 

I looked at the `set_input()` function for the Minkowski_Baseline_Model in `models/segmentation/minkowski.py` and realized that the `set_input()` for APIModel in `models/segmentation/sparseconv3d.py` is missing assigning the `self.batch_idx` variable.

I made the following edit to be able to train the network with the same command line argument as previously:
```
class APIModel(BaseModel):
.
.
.
    def set_input(self, data, device):
        self.input = data
        **self.batch_idx = data.batch.squeeze()**
        if data.y is not None:
            self.labels = data.y.to(self.device)
        else:
            self.labels = None
.
.
.
```

Would appreciate any help or comments regarding what I'm doing or if I am missing something, as I am very new to using this library.

**Comment by nicolas-chaulet** [comment]
Hi, all looks correct! Feel free to make a pull request with those, we hadn't tested sparse conv on shapenet so that's all good additions!

**Comment by chaitjo** [comment]
Sure, I can make the PR soon, thanks.

What is the difference between SparseConv3d and MinkowskiNet? (As SparseConv3d seems to allow passing `minkowski` as the backend, too.)

**Comment by nicolas-chaulet** [comment]
SparseConv3d brings an abstraction layer on top of two backends for sparse
convolutions: MinkowskiEngine and torch-sparse from MIT HAN lab.

Le lun. 14 déc. 2020 à 09:55, Chaitanya Joshi <notifications@github.com> a
écrit :
