### ISSUE TITLE
Unable to train PointNet for segmentation

### ISSUE THREAD

**Issue by chaitjo** [nicolas-chaulet/torch-points3d#521]
Hi, I believe there may be an issue with the PointNet model config for segmentation:

```
(pointcloud) root@4GPU:/mnt/sdb/chaitanya/torch-points3d# python train.py task=segmentation model_type=pointnet model_name=PointNet dataset=shapenet-fixed
DEVICE : cuda

Traceback (most recent call last):
  File "train.py", line 21, in <module>
    main()
  File "/home/chaitanya/miniconda3/envs/pointcloud/lib/python3.7/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
  File "/home/chaitanya/miniconda3/envs/pointcloud/lib/python3.7/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "/home/chaitanya/miniconda3/envs/pointcloud/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 86, in run
    job_subdir_key=None,
  File "/home/chaitanya/miniconda3/envs/pointcloud/lib/python3.7/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "train.py", line 12, in main
    trainer = Trainer(cfg)
  File "/mnt/sdb/chaitanya/torch-points3d/torch_points3d/trainer.py", line 44, in __init__
    self._initialize_trainer()
  File "/mnt/sdb/chaitanya/torch-points3d/torch_points3d/trainer.py", line 91, in _initialize_trainer
    self._model.instantiate_optimizers(self._cfg)
  File "/mnt/sdb/chaitanya/torch-points3d/torch_points3d/models/base_model.py", line 257, in instantiate_optimizers
    self._optimizer = optimizer_cls(self.parameters(), **optimizer_params)
  File "/home/chaitanya/miniconda3/envs/pointcloud/lib/python3.7/site-packages/torch/optim/adam.py", line 48, in __init__
    super(Adam, self).__init__(params, defaults)
  File "/home/chaitanya/miniconda3/envs/pointcloud/lib/python3.7/site-packages/torch/optim/optimizer.py", line 47, in __init__
    raise ValueError("optimizer got an empty parameter list")
ValueError: optimizer got an empty parameter list
```

**Comment by nicolas-chaulet** [comment]
That's strange, looks like the model does not build properly. I haven't tried PointNet ever I think so not so surprised it does not work...

**Comment by chaitjo** [comment]
Okay, any pointers on how to fix? The basic PointNet would be an essential baseline/sanity check for any new model or task.

**Comment by chaitjo** [comment]
I have implemented a fix and will submit a PR soon.

**Comment by nicolas-chaulet** [comment]
Awesome thanks!
