### ISSUE TITLE
Can't load minkowski-registration-3dmatch

### ISSUE THREAD

**Issue by egeozsoy** [nicolas-chaulet/torch-points3d#523]
Running 
`model = PretainedRegistry.from_pretrained("minkowski-registration-3dmatch").cuda()`
as recommended gives the error

` 'NoneType' object is not callable`

Maybe I am doing something wrong, not sure how this notebook would work otherwise https://github.com/nicolas-chaulet/torch-points3d/blob/93cfa0e1c2a2ad25fe358d73581bbbbc0be3e10f/notebooks/demo_registration_3dm.ipynb

**Comment by humanpose1** [comment]
Hi, 
I don't understand because it works for me. Maybe it does not download the model (It's downloaded in 
`torch_points3d/applications/weights`). 
Can you try segmentation models (such as the model in the readme) ? 
```
model = PretainedRegistry.from_pretrained("pointnet2_largemsg-s3dis-1")
```
Best,

**Comment by egeozsoy** [comment]
The error was related to minkowski engine not being correctly installed. That is my bad, maybe the error message could have been clearer though

**Comment by nicolas-chaulet** [comment]
Closing for now, glad you found the problem!

**Comment by yangninghua** [comment]
Yes, I also have this problem
```
WARNING: skipping download of existing file /media/boyun/NO_1/ubuntu16.04/deepglint/dataset/HSR工作/torch-points3d-master_new/torch_points3d/applications/weights/minkowski-registration-3dmatch.pt
Could not load Minkowski Engine, please check that it is installed correctly
Traceback (most recent call last):
  File "/home/boyun/deepglint/dataset/HSR工作/torch-points3d-master_new/ynh_new/train_registration1.py", line 89, in <module>
    main()
  File "/home/boyun/deepglint/dataset/HSR工作/torch-points3d-master_new/ynh_new/train_registration1.py", line 73, in main
    model = PretainedRegistry.from_pretrained("minkowski-registration-3dmatch").cuda()
  File "/home/boyun/deepglint/dataset/HSR工作/torch-points3d-master_new/torch_points3d/applications/pretrained_api.py", line 129, in from_pretrained
    model: BaseModel = checkpoint.create_model(dataset, weight_name=weight_name)
  File "/home/boyun/deepglint/dataset/HSR工作/torch-points3d-master_new/torch_points3d/metrics/model_checkpoint.py", line 183, in create_model
    model = instantiate_model(run_config, dataset)
  File "/home/boyun/deepglint/dataset/HSR工作/torch-points3d-master_new/torch_points3d/models/model_factory.py", line 42, in instantiate_model
    model = model_cls(model_config, "dummy", dataset, modellib)
  File "/home/boyun/deepglint/dataset/HSR工作/torch-points3d-master_new/torch_points3d/models/registration/minkowski.py", line 104, in __init__
    UnwrappedUnetBasedModel.__init__(self, option, model_type, dataset, modules)
  File "/home/boyun/deepglint/dataset/HSR工作/torch-points3d-master_new/torch_points3d/models/base_architectures/unet.py", line 363, in __init__
    self._init_from_compact_format(opt, model_type, dataset, modules_lib)
  File "/home/boyun/deepglint/dataset/HSR工作/torch-points3d-master_new/torch_points3d/models/base_architectures/unet.py", line 433, in _init_from_compact_format
    down_module = conv_cls(**args)
TypeError: 'NoneType' object is not callable
```

**Comment by nicolas-chaulet** [comment]
Looks like minkowski engine is not installed properly. Could you try to
import it in a python console?
