### ISSUE TITLE
cuda version mismatch issue when following instructions in README

### ISSUE THREAD

**Issue by OliverColeman** [nicolas-chaulet/torch-points3d#545]
I attempted to follow the instructions at https://github.com/nicolas-chaulet/torch-points3d#developer-guidelines but ran into an issue.

When I ran `poetry run python train.py task=segmentation model_type=pointnet2 model_name=pointnet2_charlesssg dataset=shapenet-fixed` I got the error below.

I tried updating pyproject.toml to specify which cuda version for the `torch_*` packages but couldn't figure out how to make it work. (there's instructions at, eg, https://github.com/rusty1s/pytorch_cluster which worked for me when not using poetry and fiddling around with the notebooks).

Error:
```
(torch-points3d-eD7SaNxM-py3.8) ➜  torch-points3d git:(master) ✗ poetry run python train.py task=segmentation model_type=pointnet2 model_name=pointnet2_charlesssg dataset=shapenet-fixed
Traceback (most recent call last):
  File "train.py", line 3, in <module>
    from torch_points3d.trainer import Trainer
  File "/home/data/work/airsight/workspace/code/torch-points3d/torch_points3d/trainer.py", line 12, in <module>
    from torch_points3d.datasets.dataset_factory import instantiate_dataset
  File "/home/data/work/airsight/workspace/code/torch-points3d/torch_points3d/datasets/dataset_factory.py", line 6, in <module>
    from torch_points3d.datasets.base_dataset import BaseDataset
  File "/home/data/work/airsight/workspace/code/torch-points3d/torch_points3d/datasets/base_dataset.py", line 8, in <module>
    import torch_geometric
  File "/home/oliver/.cache/pypoetry/virtualenvs/torch-points3d-eD7SaNxM-py3.8/lib/python3.8/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/oliver/.cache/pypoetry/virtualenvs/torch-points3d-eD7SaNxM-py3.8/lib/python3.8/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/oliver/.cache/pypoetry/virtualenvs/torch-points3d-eD7SaNxM-py3.8/lib/python3.8/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/home/oliver/.cache/pypoetry/virtualenvs/torch-points3d-eD7SaNxM-py3.8/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/oliver/.cache/pypoetry/virtualenvs/torch-points3d-eD7SaNxM-py3.8/lib/python3.8/site-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/home/oliver/.cache/pypoetry/virtualenvs/torch-points3d-eD7SaNxM-py3.8/lib/python3.8/site-packages/torch_sparse/__init__.py", line 27, in <module>
    raise RuntimeError(
RuntimeError: Detected that PyTorch and torch_sparse were compiled with different CUDA versions. PyTorch has CUDA version 10.2 and torch_sparse has CUDA version 11.0. Please reinstall the torch_sparse that matches your PyTorch install.
```

**Comment by nicolas-chaulet** [comment]
Hi @OliverColeman there are indeed situations where the default pytorch does not match the defaults torch_scatter binaries... I don't think there is a good way of solving it though, it seems that there are only bad options...
Thanks,
Nicolas

**Comment by humanpose1** [comment]
Hi @OlivierColeman, 

I sometimes have this problem. To solve it, I uninstall torch-sparse torch-cluster and so on. and I reinstall it with this command.
```
poetry run pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-1.7.0+${CUDA}.html
```
I specify the right CUDA version. 

I hope it can help !

**Comment by OliverColeman** [comment]
Thanks @humanpose1! That worked, thanks! I ended up also reinstalling torch manually because I have cuda 11 libs installed on my system, so I did (for anyone else in my situation):

`poetry run pip uninstall torch-scatter torch-sparse torch-cluster torch-geometric torch`

`poetry run pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html`

`poetry run pip install torch-scatter torch-sparse torch-cluster torch-geometric -f https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html`
