### ISSUE TITLE
API changes in MinkowskiEngine ?

### ISSUE THREAD

**Issue by laetitia-teo** [nicolas-chaulet/torch-points3d#550]
Hi, thanks for your great work.

Just trying to get a sparse conv net up and running. While trying to init one based on the README I get the following error:

```python
from torch_points3d.applications.sparseconv3d import SparseConv3d
model = SparseConv3d("unet", input_nc=3, output_nc=5, num_layers=4) # using minkowsi

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/laetitia/miniconda3/envs/general/lib/python3.8/site-packages/torch_points3d/applications/sparseconv3d.py", line 63, in SparseConv3d
    return factory.build()
  File "/home/laetitia/miniconda3/envs/general/lib/python3.8/site-packages/torch_points3d/applications/modelfactory.py", line 73, in build
    return self._build_unet()
  File "/home/laetitia/miniconda3/envs/general/lib/python3.8/site-packages/torch_points3d/applications/sparseconv3d.py", line 75, in _build_unet
    return SparseConv3dUnet(model_config, None, None, modules_lib, **self.kwargs)
  File "/home/laetitia/miniconda3/envs/general/lib/python3.8/site-packages/torch_points3d/applications/sparseconv3d.py", line 95, in __init__
    super().__init__(model_config, model_type, dataset, modules)
  File "/home/laetitia/miniconda3/envs/general/lib/python3.8/site-packages/torch_points3d/models/base_architectures/unet.py", line 351, in __init__
    self._init_from_compact_format(opt, model_type, dataset, modules_lib)
  File "/home/laetitia/miniconda3/envs/general/lib/python3.8/site-packages/torch_points3d/models/base_architectures/unet.py", line 421, in _init_from_compact_format
    down_module = conv_cls(**args)
  File "/home/laetitia/miniconda3/envs/general/lib/python3.8/site-packages/torch_points3d/modules/SparseConv3d/modules.py", line 118, in __init__
    conv(
  File "/home/laetitia/miniconda3/envs/general/lib/python3.8/site-packages/torch_points3d/modules/SparseConv3d/nn/minkowski.py", line 15, in __init__
    super().__init__(
TypeError: __init__() got an unexpected keyword argument 'has_bias'
```

A [very quick googling](https://github.com/zgojcic/3D_multiview_reg/issues/15) indicates that this is a change in ME's API, what do you think ? How can I go around this ?

**Comment by nicolas-chaulet** [comment]
Hi, yes that's correct. You can force the install of v0.4.3, this will fix your bugs. We will be updating to 0.5 soon!

**Comment by laetitia-teo** [comment]
Thanks a lot ! Seems the MinkowskiEngine people themselves haven't updated all their examples either. Looking forward to the update !
