### ISSUE TITLE
PointNet2 instantiation

### ISSUE THREAD

**Issue by mees** [nicolas-chaulet/torch-points3d#591]
Hi,
I would like to instantiate a pointnet2 encoder and I am not sure how to do this. I would like to have 3 PointnetSAModules and 2 FCs.
I am not sure if this how one should do the instantiation or if this is supported, but the following doesn't seem to work. What would the correct instantiation be?

```
from torch_points3d.applications.pointnet2 import PointNet2
net = PointNet2(architecture="encoder", input_nc=3, num_layers=3, output_ncint=512)
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/meeso/.virtualenvs/lang2control_py38/lib/python3.8/site-packages/torch_points3d/applications/pointnet2.py", line 55, in PointNet2
    return factory.build()
  File "/home/meeso/.virtualenvs/lang2control_py38/lib/python3.8/site-packages/torch_points3d/applications/modelfactory.py", line 75, in build
    return self._build_encoder()
  File "/home/meeso/.virtualenvs/lang2control_py38/lib/python3.8/site-packages/torch_points3d/applications/pointnet2.py", line 79, in _build_encoder
    model_config = OmegaConf.load(path_to_model)
  File "/home/meeso/.virtualenvs/lang2control_py38/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 253, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/meeso/.virtualenvs/lang2control_py38/lib/python3.8/site-packages/torch_points3d/applications/conf/pointnet2/encoder_3_ss.yaml'
```

**Comment by mees** [comment]
Running the following example leads to the same error.
https://github.com/nicolas-chaulet/torch-points3d/blob/master/examples/pointnet2_classification_forward.py

**Comment by CCInc** [comment]
It looks like there's not a single scale encoder architecture defined. Take a look at https://github.com/nicolas-chaulet/torch-points3d/tree/master/torch_points3d/applications/conf/pointnet2 and you can see what configs there are. For a multi-scale encoder architecture:

```
from torch_points3d.applications.pointnet2 import PointNet2
net = PointNet2(architecture="encoder", input_nc=3, num_layers=3, output_ncint=512, multiscale=True)
```

Or you can try one of the unet architectures.

**Comment by mees** [comment]
Thanks @CCInc ! Given that the example scripts are currently not working, I would suggest either adding the missing config or fixing the example to instantiate the multiscale conf.

**Comment by CCInc** [comment]
I'll take a look after this semester ends on redoing a lot of the broken pn++ things :)
