### ISSUE TITLE
MinkowskiEngine==0.5.3 Compatibility issue

### ISSUE THREAD

**Issue by austingreisman** [nicolas-chaulet/torch-points3d#596]
Hello, it seems there's an issue with Minkowski 0.5.3. I'm attempting to test your,
`from torch_points3d.applications.sparseconv3d import SparseConv3d`
`model = SparseConv3d("unet", input_nc=3, output_nc=5, num_layers=4)`
but receive the following errors

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/14amfg/repos/ML/lib/python3.8/site-packages/torch_points3d/applications/sparseconv3d.py", line 63, in SparseConv3d
    return factory.build()
  File "/home/14amfg/repos/ML/lib/python3.8/site-packages/torch_points3d/applications/modelfactory.py", line 73, in build
    return self._build_unet()
  File "/home/14amfg/repos/ML/lib/python3.8/site-packages/torch_points3d/applications/sparseconv3d.py", line 75, in _build_unet
    return SparseConv3dUnet(model_config, None, None, modules_lib, **self.kwargs)
  File "/home/14amfg/repos/ML/lib/python3.8/site-packages/torch_points3d/applications/sparseconv3d.py", line 95, in __init__
    super().__init__(model_config, model_type, dataset, modules)
  File "/home/14amfg/repos/ML/lib/python3.8/site-packages/torch_points3d/models/base_architectures/unet.py", line 351, in __init__
    self._init_from_compact_format(opt, model_type, dataset, modules_lib)
  File "/home/14amfg/repos/ML/lib/python3.8/site-packages/torch_points3d/models/base_architectures/unet.py", line 421, in _init_from_compact_format
    down_module = conv_cls(**args)
  File "/home/14amfg/repos/ML/lib/python3.8/site-packages/torch_points3d/modules/SparseConv3d/modules.py", line 118, in __init__
    conv(
  File "/home/14amfg/repos/ML/lib/python3.8/site-packages/torch_points3d/modules/SparseConv3d/nn/minkowski.py", line 15, in __init__
    super().__init__(
TypeError: __init__() got an unexpected keyword argument 'has_bias'

**Comment by austingreisman** [comment]
Well... to remove the error, you need to edit
`python3.8/site-packages/torch_points3d/modules/SparseConv3d/nn/minkowski.py`

`class Conv3d(ME.MinkowskiConvolution):
    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        kernel_size: int = 3,
        stride: int = 1,
        dilation: int = 1,
        bias: bool = False,
    ) -> None:
        super().__init__(
            in_channels,
            out_channels,
            kernel_size=kernel_size,
            stride=stride,
            dilation=dilation,
            dimension=3,
            has_bias=bias,
        )


class Conv3dTranspose(ME.MinkowskiConvolutionTranspose):
    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        kernel_size: int = 3,
        stride: int = 1,
        dilation: int = 1,
        bias: bool = False,
    ) -> None:
        super().__init__(
            in_channels,
            out_channels,
            kernel_size=kernel_size,
            stride=stride,
            dilation=dilation,
            dimension=3,
            has_bias=bias,
        )
`

You remove both `has_bias-bias` lines.

**Comment by austingreisman** [comment]
Strange, I looked at the available [https://github.com/nicolas-chaulet/torch-points3d/blob/98eed17c6bf4d38c33325d4f29357076c35a3f07/torch_points3d/modules/SparseConv3d/nn/minkowski.py#L5](minkowski.py) from this Git and it has an implementation that works...

**Comment by CCInc** [comment]
You installed from `pip`? the latest source might not be packaged yet

**Comment by austingreisman** [comment]
I did install from `pip`. Either way, if other people have the same issue before the package is sourced, they know now!

**Comment by CCInc** [comment]
@nicolas-chaulet could we look at getting a new version published? It's been a few months since the last update. In the meantime if anyone needs it they can install using git 😄 

`pip install git+https://github.com/nicolas-chaulet/torch-points3d.git`

**Comment by nicolas-chaulet** [comment]
Done!! CLosing now
