### ISSUE TITLE
multiscale_data error when performing KPConv benchmark configuration

### ISSUE THREAD

**Issue by X-Lai** [nicolas-chaulet/torch-points3d#606]
Firstly, thanks a lot for your wonderful work! 
However, when I try to use the command "python train.py task=segmentation model_type=kpconv model_name=KPConvPaper dataset=s3disfused training=s3dis_benchmark/kpconv" to run the KPConv benchmark, I meet the following error. 

```
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    main()
  File "/home/xinlai/miniconda3_pytorch1.8.1/lib/python3.7/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
  File "/home/xinlai/miniconda3_pytorch1.8.1/lib/python3.7/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "/home/xinlai/miniconda3_pytorch1.8.1/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 86, in run
    job_subdir_key=None,
  File "/home/xinlai/miniconda3_pytorch1.8.1/lib/python3.7/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "train.py", line 13, in main
    trainer.train()
  File "/home/xinlai/3d/torch-points3d/torch_points3d/trainer.py", line 140, in train
    self._train_epoch(epoch)
  File "/home/xinlai/3d/torch-points3d/torch_points3d/trainer.py", line 190, in _train_epoch
    for i, data in enumerate(tq_train_loader):
  File "/home/xinlai/miniconda3_pytorch1.8.1/lib/python3.7/site-packages/tqdm/std.py", line 1171, in __iter__
    for obj in iterable:
  File "/home/xinlai/miniconda3_pytorch1.8.1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/xinlai/miniconda3_pytorch1.8.1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/xinlai/miniconda3_pytorch1.8.1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/xinlai/miniconda3_pytorch1.8.1/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/xinlai/miniconda3_pytorch1.8.1/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/xinlai/miniconda3_pytorch1.8.1/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/xinlai/3d/torch-points3d/torch_points3d/datasets/base_dataset.py", line 157, in _collate_fn
    return collate_fn(batch)
  File "/home/xinlai/3d/torch-points3d/torch_points3d/datasets/multiscale_data.py", line 93, in from_data_list
    batch = Batch.from_data_list(data_list)
  File "/home/xinlai/miniconda3_pytorch1.8.1/lib/python3.7/site-packages/torch_geometric/data/batch.py", line 45, in from_data_list
    assert 'batch' not in keys and 'ptr' not in keys
AssertionError
```

It seems that when passing the python list of selected point clouds into the collate function, the point cloud data structure still has the key of 'batch' or 'ptr'. Would you help me to handle this problem? Thanks a lot! @nicolas-chaulet @liubigli @CCInc

**Comment by fclairec** [comment]
Hi, I have a similar problem when using PointGroup on S3DIS 

config.yml:
![image](https://user-images.githubusercontent.com/59439696/118794420-db149b80-b899-11eb-85a5-841784c95059.png)


[2021-05-19 09:42:32,741][torch_points3d.datasets.base_dataset][INFO] - The models will be selected using the metrics on following dataset:  val
[2021-05-19 09:42:54,787][torch_points3d.trainer][INFO] - EPOCH 1 / 100
  0%|                                                                                                                                                                                                                | 0/188 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 14, in main
    trainer.train()
  File "/home/appuser/torch-points3d-master/torch_points3d/trainer.py", line 140, in train
    self._train_epoch(epoch)
  File "/home/appuser/torch-points3d-master/torch_points3d/trainer.py", line 190, in _train_epoch
    for i, data in enumerate(tq_train_loader):
  File "/home/appuser/miniconda/lib/python3.8/site-packages/tqdm/std.py", line 1107, in __iter__
    for obj in iterable:
  File "/home/appuser/miniconda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/appuser/miniconda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/appuser/miniconda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/appuser/miniconda/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/appuser/miniconda/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/appuser/miniconda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/appuser/torch-points3d-master/torch_points3d/datasets/base_dataset.py", line 157, in _collate_fn
    return collate_fn(batch)
  File "/home/appuser/miniconda/lib/python3.8/site-packages/torch_geometric/data/batch.py", line 45, in from_data_list
    assert 'batch' not in keys and 'ptr' not in keys
AssertionError



I would also be super grateful for some help on this

**Comment by nicolas-chaulet** [comment]
Looks like we have a bug here that might be due to an upgrade to the latest pytorch geometric

**Comment by nicolas-chaulet** [comment]
Could you please checkout that branch #608 and let me know if that solves it?
Thanks!

**Comment by X-Lai** [comment]
It seems that I meet another error due to checking out to this branch.

```
Traceback (most recent call last):
  File "train.py", line 2, in <module>
    from hydra.core.global_hydra import GlobalHydra
ModuleNotFoundError: No module named 'hydra.core'
```

It seems that I can successfully import hydra, but I can't import hydra.core. Could you help me to solve this problem?
Thanks a lot! @nicolas-chaulet

**Comment by nicolas-chaulet** [comment]
Could you update your packages? This is because we have updated to the latest version of Hydra: `poetry install`

**Comment by fclairec** [comment]
Hi Nicolas, your fix did the trick for me 
Thanks a lot for your reactiveness!

**Comment by nicolas-chaulet** [comment]
Thanks for the testing, merging now
