### ISSUE TITLE
Forward pass on the data doesn't work using the forward scripts.

### ISSUE THREAD

**Issue by diwakar-ravichandran** [nicolas-chaulet/torch-points3d#636]
I have sort of been able to isolate the issue. It is to do with this line of code not working

setattr(checkpoint.data_config, "class", train_dataset_cls.FORWARD_CLASS) 

From what I understand it should be updating checkpoint.data_config.class from shapenet.ShapeNetDataset to forward.shapenet.ForwardShapeNetDataset and then call the member function predict_original_samples to get the final output. But for some reason the setattr function doesn't seem to be updating the class name and when I tried debugging multiple times, I failed miserably. Could appreciate any help I can get..

The versions I am using are:
    - python 3.7.10
    - torch 1.8.0
    - torchvision 0.9.0

Will be happy to provide any other information that could help resolve this issue

**Comment by CCInc** [comment]
Hi Diwakar, 

I'm guessing you're using the `forward_scripts/forward.py` script for the forward pass? Please try the following for me:

In  `forward_scripts/forward.py` replace `@hydra.main(config_path="conf/config.yaml")` with `@hydra.main(config_path="conf", config_name="config")`. Let me know if that changes anything.

Also, please add a `print(checkpoint.data_config)` statement before and after `setattr(checkpoint.data_config, "class", train_dataset_cls.FORWARD_CLASS)`, as well as before `model = checkpoint.create_model` and post it here, that can help me debug more.

**Comment by hadilou** [comment]
Hi @CCInc ,

I am also not able to run the provided forward script at `forward_scripts/forward.py` .  I thought it would make sense to comment on an exisitng issue then creating a new one. Please, find the output error below. 

``` 
$ python forward_scripts/forward.py
 /home/usr/anaconda3/envs/points3d/lib/python3.8/site-packages/hydra/_internal/config_repository.py:229: UserWarning:
In config: 'optional: true' is deprecated.
Use 'optional dataset: shapenet' instead.
Support for the old style will be removed in Hydra 1.2
  warnings.warn(msg)
[2021-07-14 17:30:45,107][__main__][INFO] - DEVICE : cpu
[2021-07-14 17:30:45,107][torch_points3d.metrics.model_checkpoint][INFO] - Loading checkpoint from /home/khadje/Documents/Workspace/torch-points3d/outputs/2021-07-12/16-36-52/pointnet2_charlesssg.pt
Error executing job with overrides: []
Traceback (most recent call last):
  File "forward_scripts/forward.py", line 85, in main
    model = checkpoint.create_model(checkpoint.dataset_properties, weight_name=cfg.weight_name)
  File "/home/usr/Documents/Workspace/torch-points3d/forward_scripts/../torch_points3d/metrics/model_checkpoint.py", line 185, in create_model
    model = instantiate_model(OmegaConf.create(run_config), dataset)
  File "/home/usr/Documents/Workspace/torch-points3d/forward_scripts/../torch_points3d/models/model_factory.py", line 25, in instantiate_model
    resolve_model(model_config, dataset, task)
  File "/home/usr/Documents/Workspace/torch-points3d/forward_scripts/../torch_points3d/utils/model_building_utils/model_definition_resolver.py", line 10, in resolve_model
    "FEAT": max(dataset.feature_dimension, 0),
AttributeError: 'dict' object has no attribute 'feature_dimension'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```


I (slightly) modified the `forward_scripts/forward.py` script as follows
``` 
import torch
import hydra
import logging
from omegaconf import OmegaConf
from omegaconf import DictConfig
import os
import sys
import numpy as np
from typing import Dict

DIR = os.path.dirname(os.path.realpath(__file__))
ROOT = os.path.join(DIR, "..")
sys.path.insert(0, ROOT)

# Import building function for model and dataset
from torch_points3d.datasets.dataset_factory import instantiate_dataset, get_dataset_class
from torch_points3d.models.model_factory import instantiate_model

# Import BaseModel / BaseDataset for type checking
from torch_points3d.models.base_model import BaseModel
from torch_points3d.datasets.base_dataset import BaseDataset

# Import from metrics
from torch_points3d.metrics.colored_tqdm import Coloredtqdm as Ctq
from torch_points3d.metrics.model_checkpoint import ModelCheckpoint

# Utils import
from torch_points3d.utils.colors import COLORS

log = logging.getLogger(__name__)


def save(prefix, predicted):
    for key, value in predicted.items():
        filename = os.path.splitext(key)[0]
        out_file = filename + "_pred"
        np.save(os.path.join(prefix, out_file), value)


def run(model: BaseModel, dataset, device, output_path):
    loaders = dataset.test_dataloaders
    predicted: Dict = {}
    for loader in loaders:
        loader.dataset.name
        with Ctq(loader) as tq_test_loader:
            for data in tq_test_loader:
                with torch.no_grad():
                    model.set_input(data, device)
                    model.forward()
                predicted = {**predicted, **dataset.predict_original_samples(data, model.conv_type, model.get_output())}

    save(output_path, predicted)


@hydra.main(config_path="conf",config_name="config")
def main(cfg: DictConfig):
    OmegaConf.set_struct(cfg, False)

    # Get device
    device = torch.device("cuda" if (torch.cuda.is_available() and cfg.cuda) else "cpu")
    log.info("DEVICE : {}".format(device))

    # Enable CUDNN BACKEND
    torch.backends.cudnn.enabled = cfg.enable_cudnn

    # Checkpoint
    checkpoint = ModelCheckpoint(cfg.checkpoint_dir, cfg.model_name, cfg.weight_name, strict=True)

    # Setup the dataset config
    # Generic config
    train_dataset_cls = get_dataset_class(checkpoint.data_config)
    setattr(checkpoint.data_config, "class", train_dataset_cls.FORWARD_CLASS)
    setattr(checkpoint.data_config, "dataroot", cfg.input_path)

    # Datset specific configs
    # print(cfg)
    if cfg.dataset.data:
        for key, value in cfg.dataset.data.items():
            checkpoint.data_config.update({key: value})
    if cfg.dataset:
        for key, value in cfg.dataset.items():
            checkpoint.dataset_properties.update({key:value})

    # Create dataset and mdoel
    model = checkpoint.create_model(checkpoint.dataset_properties, weight_name=cfg.weight_name)
    log.info(model)
    log.info("Model size = %i", sum(param.numel() for param in model.parameters() if param.requires_grad))

    # Set dataloaders
    dataset = instantiate_dataset(checkpoint.data_config)
    dataset.create_dataloaders(
        model, cfg.batch_size, cfg.shuffle, cfg.num_workers, False,
    )
    log.info(dataset)

    model.eval()
    if cfg.enable_dropout:
        model.enable_dropout_in_eval()
    model = model.to(device)

    # Run training / evaluation
    if not os.path.exists(cfg.output_path):
        os.makedirs(cfg.output_path)

    run(model, dataset, device, cfg.output_path)


if __name__ == "__main__":
    main()
```

And here is my `forward_scripts/conf/config.yaml` configuration file

``` 
num_workers: 2
batch_size: 16
cuda: 0
weight_name: "miou" # Used during resume, select with model to load from [miou, macc, acc..., latest]
enable_cudnn: True
checkpoint_dir: "/home/usr/Documents/Workspace/torch-points3d/outputs/2021-07-12/16-36-52" # "{your_path}/outputs/2020-01-28/11-04-13" for example
model_name: pointnet2_charlesssg
enable_dropout: False
output_path: "/home/usr/Documents/Workspace/preds_points3d/out" # Where the output goes
input_path: "/home/usr/Documents/Workspace/torch-points3d/data/shapenet/raw/03790512" # Folder where to find the data

# Dataset specific
defaults:
    - dataset: "shapenet"
      optional: True
```

Priting out the `cfg` object in `forward_scripts/forwardpy` right before the line `if cfg.dataset.data:` gives the following:

``` 
{'dataset': {'data': {'forward_category': 'Cap'}}, 'num_workers': 2, 'batch_size': 16, 'cuda': 0, 'weight_name': 'miou', 'enable_cudnn': True, 'checkpoint_dir': '/home/usr/Documents/Workspace/torch-points3d/outputs/2021-07-12/16-36-52', 'model_name': 'pointnet2_charlesssg', 'enable_dropout': False, 'output_path': '/home/usr/Documents/Workspace/preds_points3d/out', 'input_path': '/home/usr/Documents/Workspace/torch-points3d/data/shapenet/raw/03790512'}
```

**Comment by harry1576** [comment]
I did as you suggested @CCInc . 

> In `forward_scripts/forward.py` replace `@hydra.main(config_path="conf/config.yaml")` with `@hydra.main(config_path="conf", config_name="config")`. Let me know if that changes anything.

-> Did not change anything



> Also, please add a `print(checkpoint.data_config)` statement before and after `setattr(checkpoint.data_config, "class", train_dataset_cls.FORWARD_CLASS)`, as well as before `model = checkpoint.create_model` and post it here, that can help me debug more.

before setattr(checkpoint.data_config, "class"):
``` {'task': 'segmentation', 'class': 'vine.VineDataset', 'dataroot': 'data', 'normal': False, 'use_category': True, 'feature_dimension': 0, 'first_subsampling': 0.001, 'pre_transforms': [{'transform': 'GridSampling3D', 'params': {'size': 0.0005}}, {'transform': 'GridSphereSampling', 'params': {'radius': 0.1, 'grid_size': 0.1}}]} ```

after setattr(checkpoint.data_config, "class"):
``` {'task': 'segmentation', 'class': 'vine.VineDataset', 'dataroot': 'data', 'normal': False, 'use_category': True, 'feature_dimension': 0, 'first_subsampling': 0.001, 'pre_transforms': [{'transform': 'GridSampling3D', 'params': {'size': 0.0005}}, {'transform': 'GridSphereSampling', 'params': {'radius': 0.1, 'grid_size': 0.1}}]} ```


before model = checkpoint.create_model: ``` {'task': 'segmentation', 'class': 'vine.VineDataset', 'dataroot': 'data', 'normal': False, 'use_category': True, 'feature_dimension': 0, 'first_subsampling': 0.001, 'pre_transforms': [{'transform': 'GridSampling3D', 'params': {'size': 0.0005}}, {'transform': 'GridSphereSampling', 'params': {'radius': 0.1, 'grid_size': 0.1}}]} ```

After model: cannot do one after model as I get the following error, during model creation: 
```
Traceback (most recent call last):
  File "forward_scripts/forward.py", line 87, in main
    model = checkpoint.create_model(checkpoint.dataset_properties, weight_name=cfg.weight_name)
  File "/local/vine-seg/torch-points3d/forward_scripts/../torch_points3d/metrics/model_checkpoint.py", line 186, in create_model
    model = instantiate_model(OmegaConf.create(run_config), dataset)
  File "/local/vine-seg/torch-points3d/forward_scripts/../torch_points3d/models/model_factory.py", line 23, in instantiate_model
    resolve_model(model_config, dataset, task)
  File "/local/vine-seg/torch-points3d/forward_scripts/../torch_points3d/utils/model_building_utils/model_definition_resolver.py", line 10, in resolve_model
    "FEAT": max(dataset.feature_dimension, 0),
AttributeError: 'dict' object has no attribute 'feature_dimension'
```

Thanks :)

**Comment by diwakar-ravichandran** [comment]
@harry1576 @hadilou thank you for responding on my behalf, as for the Attribute error in order to fix it, what I did was, 
In
> torch-points3d/torch_points3d/utils/model_building_utils/model_definition_resolver.py 

Added one line of code,

'dataset = DictConfig(dataset)' 

And this fixed the issue with Attribute

**Comment by hadilou** [comment]
Hey @diwakar-ravichandran 

Do you mind sharing your forward script and config file? The change you mentioned does not seem to fix the issue for me.

**Comment by harry1576** [comment]
Thanks for the insight @diwakar-ravichandran  , however this does not solve the issue for me . 
As I now get the error:
`AttributeError: 'dict' object has no attribute 'num_classes'`

**Comment by ThGravo** [comment]
I'm also struggling with this example!

**Comment by diwakar-ravichandran** [comment]
@hadilou @harry1576 I have raised a PR for the fix you can have a look at it and check if it still doesn't work. 

#643 Hopefully this resolves the issue

**Comment by harry1576** [comment]
Hi Guys,

I seem to still be having the same issue. 
Has anyone made any progress in regards to resolving it?

Here is the snippet of code:
` 
    print(cfg.input_path)
    setattr(checkpoint.data_config, "dataroot", cfg.input_path)
    print(checkpoint.data_config.dataroot)
    
    assert checkpoint.data_config.dataroot == cfg.input_path
`

And the output:
`
    /local/torch-points3d/forward_scripts/test_data
    data
    Error executing job with overrides: []
    Traceback (most recent call last):
      File "forward_scripts/forward.py", line 95, in main
        assert checkpoint.data_config.dataroot == cfg.input_path
    AssertionError
    
    Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

`
Any help would be appreciated. 

Cheers,
Harry

**Comment by diwakar-ravichandran** [comment]
Hey @harry1576 sorry I did not have time to go back and see this code. Can you give a full stack trace? Like what are you running, and what is being passed as cfg? Because from what I can see the setattr is still failing. I am not sure how to fix it.

**Comment by harry1576** [comment]
> ot have time to go back and see this code. Can you give a full stack trace? Like what are you running, and what is being passed as cfg? Because from what I can see the setattr is still failing. I am not sure h

Yes that is correct, the setattr is failing. It happens on anything that is using the forward.py script.
Cheers,
Harry

**Comment by PeterTor** [comment]
@harry1576 
add the following to the initialization of ModelCheckpoint(object) 
self.data_config = OmegaConf.create(self._checkpoint.run_config["data"])

and remove the property for self.data_config

**Comment by Flo11** [comment]
Hi @PeterTor 
Could you provide more information about your fix because I tried to add :
self.data_config = OmegaConf.create(self._checkpoint.run_config["data"])
in torch-points3d/torch-points3d/metrics/model_checkpoint.py file

but I got the followinf error :

  File "/home/pc/Documents/computer-vision/torch-points3d/forward_scripts/../torch_points3d/metrics/model_checkpoint.py", line 170, in __init__
    self.data_config = OmegaConf.create(self._checkpoint.run_config["data"])
AttributeError: can't set attribute

Thanks for your help
