### ISSUE TITLE
Processing scannet fails

### ISSUE THREAD

**Issue by Alphastrick** [nicolas-chaulet/torch-points3d#639]
**Description**
During using VoteNet2 on Scannet V2, an error occurred during processing the data.

**Executed command**
```
python train.py task=object_detection model_name=VoteNetPaper models=object_detection/votenet2 data=object_detection/scannet
```

**Error**
```
Traceback (most recent call last):
  File "train.py", line 13, in main
    trainer = Trainer(cfg)
  File "D:\torch_points3d\trainer.py", line 44, in __init__
    self._initialize_trainer()
  File "D:\torch_points3d\trainer.py", line 91, in _initialize_trainer
    self._dataset: BaseDataset = instantiate_dataset(self._cfg.data)
  File "D:\torch_points3d\datasets\dataset_factory.py", line 46, in instantiate_dataset
    dataset = dataset_cls(dataset_config)
  File "D:\torch_points3d\datasets\object_detection\scannet.py", line 190, in __init__
    is_test=is_test,
  File "D:\torch_points3d\datasets\object_detection\scannet.py", line 44, in __init__
    super(ScannetObjectDetection, self).__init__(*args, **kwargs)
  File "D:\torch_points3d\datasets\segmentation\scannet.py", line 473, in __init__
    super().__init__(root, transform, pre_transform, pre_filter)
  File "D:\venv\lib\site-packages\torch_geometric\data\in_memory_dataset.py", line 60, in __init__
    super().__init__(root, transform, pre_transform, pre_filter)
  File "D:\venv\lib\site-packages\torch_geometric\data\dataset.py", line 86, in __init__
    self._process()
  File "D:\venv\lib\site-packages\torch_geometric\data\dataset.py", line 165, in _process
    self.process()
  File "D:\torch_points3d\datasets\object_detection\scannet.py", line 164, in process
    super().process()
  File "D:\torch_points3d\datasets\segmentation\scannet.py", line 765, in process
    datas = [self.pre_transform(data) for data in datas]
  File "D:\torch_points3d\datasets\segmentation\scannet.py", line 765, in <listcomp>
    datas = [self.pre_transform(data) for data in datas]
  File "D:\venv\lib\site-packages\torch_geometric\transforms\compose.py", line 15, in __call__
    data = transform(data)
  File "D:\torch_points3d\core\data_transform\grid_transform.py", line 135, in __call__
    data = self._process(data)
  File "D:\torch_points3d\core\data_transform\grid_transform.py", line 124, in _process
    data = group_data(data, cluster, unique_pos_indices, mode=self._mode)
  File "D:\torch_points3d\core\data_transform\grid_transform.py", line 74, in group_data
    item = F.one_hot(item - item_min)
RuntimeError: one_hot is only applicable to index tensor.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by nicolas-chaulet** [comment]
How did you fix that?

**Comment by Alphastrick** [comment]
I switched to the scannet-fixed version.
