### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu

### ISSUE THREAD

**Issue by LucaRom** [nicolas-chaulet/torch-points3d#640]
This error happens when I increase the number of files in the dataset while training in KPconv (ie : using a subset wont raise the error, but the full dataset will).

It seems to trigger right after the test is finished. It is a bit hard to debug since I need to run through a full epoch each time. I'm currently looking for a way to print all the tensors and their device at that time.

I run this command : `train.py task=segmentation models=segmentation/kpconv model_name=KPConvPaper data=segmentation/dales training=kpconv`

and here is the error : 

```
100%|██████████| 1798/1798 [34:49<00:00,  1.16s/it, data_loading=0.005, iteration=0.586, train_acc=47.96, train_loss_seg=1.446, train_macc=19.42, train_miou=12.55)]
[2021-07-14 11:43:21,727][torch_points3d.trainer][INFO] - Learning rate = 0.009885
100%|█████████▉| 806/807 [12:41<00:00,  1.06it/s, test_acc=56.59, test_loss_seg=1.066, test_macc=15.98, test_miou=10.28)]
Traceback (most recent call last):
  File "/wspace/disk01/lidar/classification_pts/torch-points3d/train.py", line 14, in main
    trainer.train()
  File "/export/sata01/wspace/lidar/classification_pts/torch-points3d/torch_points3d/trainer.py", line 154, in train
    self._test_epoch(epoch, "test")
  File "/export/sata01/wspace/lidar/classification_pts/torch-points3d/torch_points3d/trainer.py", line 250, in _test_epoch
    self._model.forward(epoch=epoch)
  File "/export/sata01/wspace/lidar/classification_pts/torch-points3d/torch_points3d/models/segmentation/kpconv.py", line 112, in forward
    data = self.down_modules[i](data, precomputed=self.pre_computed)
  File "/wspace/disk01/conda_envs/torch_points3d/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/export/sata01/wspace/lidar/classification_pts/torch-points3d/torch_points3d/modules/KPConv/blocks.py", line 280, in forward
    data = block(data, precomputed=precomputed)
  File "/wspace/disk01/conda_envs/torch_points3d/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/export/sata01/wspace/lidar/classification_pts/torch-points3d/torch_points3d/modules/KPConv/blocks.py", line 201, in forward
    output = self.kp_conv(output, precomputed=precomputed)
  File "/wspace/disk01/conda_envs/torch_points3d/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/export/sata01/wspace/lidar/classification_pts/torch-points3d/torch_points3d/modules/KPConv/blocks.py", line 75, in forward
    query_data = self.sampler(data.clone())
  File "/export/sata01/wspace/lidar/classification_pts/torch-points3d/torch_points3d/core/data_transform/grid_transform.py", line 135, in __call__
    data = self._process(data)
  File "/export/sata01/wspace/lidar/classification_pts/torch-points3d/torch_points3d/core/data_transform/grid_transform.py", line 124, in _process
    data = group_data(data, cluster, unique_pos_indices, mode=self._mode)
  File "/export/sata01/wspace/lidar/classification_pts/torch-points3d/torch_points3d/core/data_transform/grid_transform.py", line 78, in group_data
    data[key] = scatter_mean(item, cluster, dim=0)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/wspace/disk01/conda_envs/torch_points3d/lib/python3.7/site-packages/torch_scatter/scatter.py", line 22, in scatter_mean
            size[dim] = int(index.max()) + 1
        out = torch.zeros(size, dtype=src.dtype, device=src.device)
        return out.scatter_add_(dim, index, src)
               ~~~~~~~~~~~~~~~~ <--- HERE
    else:
        return out.scatter_add_(dim, index, src)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

Thank you for the help!

**Comment by CamilleMaurice** [comment]
Hi ! Just to let you know I am experiencing the same issue.  If I find a solution I'll let you know, it might help other people as well.
For now I am just checking the device as such :         
 l78 https://gsvision.geo-sat.com/tf260/lab/tree/Camille/Points3d/torch-points3d/torch_points3d/core/data_transform/grid_transform.py   
print(item.get_device())
print(cluster.get_device())
data[key] = scatter_mean(item, cluster, dim=0)
