### ISSUE TITLE
Visualization problem

### ISSUE THREAD

**Issue by OOps717** [nicolas-chaulet/torch-points3d#649]
Hello,

First I would like to thank you for this framework! My problem is to visualize the result of a neural network performing a segmentation task. I am trying to use the forward.py script in the forward_scripts folder for the visualization, having originally trained the kpconv neural network on the shapenet dataset and changed the configuration file. However, I encountered this error:

```
Traceback (most recent call last):
  File "/home/sultanov/CloudsSegmentation/torch-points3d/forward_scripts/../torch_points3d/models/segmentation/kpconv.py", line 31, in __init__
    self._weight_classes = dataset.weight_classes
AttributeError: 'dict' object has no attribute 'weight_classes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "forward_scripts/forward.py", line 84, in main
    model = checkpoint.create_model(checkpoint.dataset_properties, weight_name=cfg.weight_name)
  File "/home/sultanov/CloudsSegmentation/torch-points3d/forward_scripts/../torch_points3d/metrics/model_checkpoint.py", line 174, in create_model
    model = instantiate_model(OmegaConf.create(run_config), dataset)
  File "/home/sultanov/CloudsSegmentation/torch-points3d/forward_scripts/../torch_points3d/models/model_factory.py", line 44, in instantiate_model
    model = model_cls(model_config, "dummy", dataset, modellib)
  File "/home/sultanov/CloudsSegmentation/torch-points3d/forward_scripts/../torch_points3d/models/segmentation/kpconv.py", line 33, in __init__
    self._weight_classes = dataset.weight_classes
AttributeError: 'dict' object has no attribute 'weight_classes'
```
By giving the value None to self._weight_classes, I got the following error: 

```
Traceback (most recent call last):
  File "forward_scripts/forward.py", line 104, in main
    run(model, dataset, device, cfg.output_path)
  File "forward_scripts/forward.py", line 46, in run
    for data in tq_test_loader:
  File "/home/sultanov/CloudsSegmentation/pcb/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/sultanov/CloudsSegmentation/pcb/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/sultanov/CloudsSegmentation/pcb/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/sultanov/CloudsSegmentation/pcb/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/sultanov/CloudsSegmentation/pcb/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/sultanov/CloudsSegmentation/pcb/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/sultanov/CloudsSegmentation/pcb/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/sultanov/CloudsSegmentation/torch-points3d/forward_scripts/../torch_points3d/datasets/base_dataset.py", line 157, in _collate_fn
    return collate_fn(batch)
  File "/home/sultanov/CloudsSegmentation/pcb/lib/python3.8/site-packages/torch_geometric/data/batch.py", line 44, in from_data_list
    keys = list(set(data_list[0].keys) - set(exclude_keys))
  File "/home/sultanov/CloudsSegmentation/pcb/lib/python3.8/site-packages/torch_geometric/data/data.py", line 123, in __getitem__
    return getattr(self, key, None)
TypeError: getattr(): attribute name must be string


Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

Thank you in advance for your response.

**Comment by OOps717** [comment]
After some manipulation, I was able to fix the previous error. However, at this point the following error is present:
```
Traceback (most recent call last):
  File "forward_scripts/forward.py", line 107, in main
    run(model, dataset, device, cfg.output_path)
  File "forward_scripts/forward.py", line 50, in run
    predicted = {**predicted, **dataset.predict_original_samples(data, model.conv_type, model.get_output())}
AttributeError: 'ShapeNetDataset' object has no attribute 'predict_original_samples'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

Does anyone know how I can fix it?

**Comment by CCInc** [comment]
@OOps717 Hi, I think this might be fixed by #643 can you take a look?

**Comment by OOps717** [comment]
This helped me solve the first two errors, but the error with the missing predict_original_samples function remains unsolved

**Comment by diwakar-ravichandran** [comment]
@CCInc Chris, the third error faced by @OOps717 is the same as my issue that I raised. The setattr function is not able to switch between the class names. And that is causing the code to fail.

**Comment by surumetic** [comment]
The same happened with me and I dealt with this like this.  Might be an ugly way though.

```
    # setattr(checkpoint.data_config, "class", train_dataset_cls.FORWARD_CLASS)
    # setattr(checkpoint.data_config, "dataroot", cfg.input_path)
    checkpoint._checkpoint.run_config["data"]["class"] = train_dataset_cls.FORWARD_CLASS
    checkpoint._checkpoint.run_config["data"]["dataroot"] = cfg.input_path
```
