### ISSUE TITLE
Problem when running segmentation code on S3DIS dataset

### ISSUE THREAD

**Issue by bxiang233** [nicolas-chaulet/torch-points3d#675]
When I run:
python train.py task=segmentation models=segmentation/kpconv model_name=KPConvPaper data=segmentation/s3disfused training=s3dis_benchmark/kpconv

The log shows below:
[2021-09-22 10:58:21,359][torch_points3d.trainer][INFO] - DEVICE : cuda
Processing...
 94%|█████████▍| 255/272 [16:25<00:58,  3.45s/it]/cluster/scratch/bxiang/envpytorch19/lib/python3.7/site-packages/torch_geometric/data/dataset.py:171: DtypeWarning: Columns (5) have mixed types.Specify dtype option on import or set low_memory=False.
  self.process()
100%|██████████| 272/272 [17:56<00:00,  3.96s/it][2021-09-22 11:17:10,624][torch_points3d.datasets.segmentation.s3dis][INFO] - pre_collate_transform ...
[2021-09-22 11:17:10,626][torch_points3d.datasets.segmentation.s3dis][INFO] - Compose([
    PointCloudFusion(),
    SaveOriginalPosId,
    GridSampling3D(grid_size=0.04, quantize_coords=False, mode=mean),
])

Traceback (most recent call last):
  File "/cluster/scratch/bxiang/envpytorch19/lib/python3.7/site-packages/torch_geometric/data/storage.py", line 48, in __getattr__
    return self[key]
  File "/cluster/scratch/bxiang/envpytorch19/lib/python3.7/site-packages/torch_geometric/data/storage.py", line 68, in __getitem__
    return self._mapping[key]
KeyError: 'num_nodes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 13, in main
    trainer = Trainer(cfg)
  File "/cluster/scratch/bxiang/torch-points3d/torch_points3d/trainer.py", line 44, in __init__
    self._initialize_trainer()
  File "/cluster/scratch/bxiang/torch-points3d/torch_points3d/trainer.py", line 91, in _initialize_trainer
    self._dataset: BaseDataset = instantiate_dataset(self._cfg.data)
  File "/cluster/scratch/bxiang/torch-points3d/torch_points3d/datasets/dataset_factory.py", line 46, in instantiate_dataset
    dataset = dataset_cls(dataset_config)
  File "/cluster/scratch/bxiang/torch-points3d/torch_points3d/datasets/segmentation/s3dis.py", line 650, in __init__
    transform=self.train_transform,
  File "/cluster/scratch/bxiang/torch-points3d/torch_points3d/datasets/segmentation/s3dis.py", line 511, in __init__
    super().__init__(root, *args, **kwargs)
  File "/cluster/scratch/bxiang/torch-points3d/torch_points3d/datasets/segmentation/s3dis.py", line 288, in __init__
    super(S3DISOriginalFused, self).__init__(root, transform, pre_transform, pre_filter)
  File "/cluster/scratch/bxiang/envpytorch19/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 57, in __init__
    super().__init__(root, transform, pre_transform, pre_filter)
  File "/cluster/scratch/bxiang/envpytorch19/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 88, in __init__
    self._process()
  File "/cluster/scratch/bxiang/envpytorch19/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 171, in _process
    self.process()
  File "/cluster/scratch/bxiang/torch-points3d/torch_points3d/datasets/segmentation/s3dis.py", line 529, in process
    super().process()
  File "/cluster/scratch/bxiang/torch-points3d/torch_points3d/datasets/segmentation/s3dis.py", line 462, in process
    train_data_list = self.pre_collate_transform(train_data_list)
  File "/cluster/scratch/bxiang/envpytorch19/lib/python3.7/site-packages/torch_geometric/transforms/compose.py", line 18, in __call__
    data = [transform(d) for d in data]
  File "/cluster/scratch/bxiang/envpytorch19/lib/python3.7/site-packages/torch_geometric/transforms/compose.py", line 18, in <listcomp>
    data = [transform(d) for d in data]
  File "/cluster/scratch/bxiang/torch-points3d/torch_points3d/core/data_transform/transforms.py", line 84, in __call__
    data = self._process(data_list)
  File "/cluster/scratch/bxiang/torch-points3d/torch_points3d/core/data_transform/transforms.py", line 70, in _process
    data = Batch.from_data_list(data_list)
  File "/cluster/scratch/bxiang/envpytorch19/lib/python3.7/site-packages/torch_geometric/data/batch.py", line 69, in from_data_list
    exclude_keys=exclude_keys,
  File "/cluster/scratch/bxiang/envpytorch19/lib/python3.7/site-packages/torch_geometric/data/collate.py", line 96, in collate
    and stores[0].num_nodes is not None):
  File "/cluster/scratch/bxiang/envpytorch19/lib/python3.7/site-packages/torch_geometric/data/storage.py", line 51, in __getattr__
    f"'{self.__class__.__name__}' object has no attribute '{key}'")
AttributeError: 'GlobalStorage' object has no attribute 'num_nodes'

Could please give me some idea where is the problem? Thank you so much!

**Comment by jeongyw12382** [comment]
How was this issue solved? I'm currently suffering from the same problem.

**Comment by bxiang233** [comment]
> How was this issue solved? I'm currently suffering from the same problem.

Hi, sorry I am not sure how to solve it... Maybe you can try to delete all the files in data/s3disfused/processed directory, and run the train.py again. Good luck!

**Comment by jeongyw12382** [comment]
Oh, thanks for the meaningful suggestion. I solve this issue by using a different configuration file.
