### ISSUE TITLE
error on unittest

### ISSUE THREAD

**Issue by tiger-bug** [nicolas-chaulet/torch-points3d#695]
Hello,

I am attempting to run torch-points3d in a docker container (similar to the one found in the ```docker``` folder).  Here is a copy of the dockerfile

```docker
FROM nvidia/cuda:10.2-devel-ubuntu18.04
ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update && apt-get install -y software-properties-common git-all libusb-1.0-0



RUN : \
    && apt-get update \
    && apt-get install -y --no-install-recommends software-properties-common \
    && add-apt-repository -y ppa:deadsnakes \
    && apt-get install -y --no-install-recommends python3.8-venv  python3.8-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && :

RUN python3.8 -m venv /venv
ENV PATH=/venv/bin:$PATH
ENV FORCE_CUDA 1
ENV TORCH_CUDA_ARCH_LIST "3.5 5.2 6.0 6.1 7.0+PTX"
RUN pip install --upgrade pip && pip install poetry
WORKDIR t3d
RUN git clone https://github.com/nicolas-chaulet/torch-points3d.git
WORKDIR torch-points3d
RUN poetry install --no-root
```
I access the docker container via the following command:
```bash
$ docker run --gpus all --rm -it -p 8888:8888 -v path/to/data:/data_folder/ $image_name
```
This opens the docker container.  Within the container, I run
```bash
root/t3d/torch_points3d $ poetry shell # This activates poetry
(activated_env) root/t3d/torch_points3d $ python -m unittest -v
```
Most of the test passes, however I get 7 errors regarding modules.  The error statements are as follows:
```
======================================================================
ERROR: test_setbackend (test.test_sparseconv.TestSparseConv)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/t3d/torch-points3d/test/test_sparseconv.py", line 14, in test_setbackend
    sp3d.nn.set_backend("torchsparse")
  File "/t3d/torch-points3d/torch_points3d/modules/SparseConv3d/nn/__init__.py", line 52, in set_backend
    exec("globals()['%s'] = modules.%s" % (val, val))
  File "<string>", line 1, in <module>
NameError: name 'modules' is not defined
```

This error is in several places.  I am not sure what the module name is.  Is this still usable even though these errors exist?  Thanks!

**Comment by tiger-bug** [comment]
Just for clarification, ```torch_points3d``` does import and I don't have minkowski engine installed.  I will install that and see if the issue persists.

**Comment by tiger-bug** [comment]
Fixed.  Problem was torchsparse was not installed within the docker container.  I also installed minkowski.  I added

```
RUN apt-get update && apt-get install -f -y libopenblas-dev \
libsparsehash-dev
RUN pip install ninja
RUN pip install --upgrade git+https://github.com/mit-han-lab/torchsparse.git@v1.4.0
RUN pip install -U MinkowskiEngine --install-option="--blas=openblas" -v --no-deps
```
Also, I would recommend to run 
```
RUN poetry config virtualenvs.create false ## run this before RUN poetry install --no-root
```
